// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// McpTokensColumns holds the columns for the "mcp_tokens" table.
	McpTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 80},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "prefix", Type: field.TypeString, Size: 16},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// McpTokensTable holds the schema information for the "mcp_tokens" table.
	McpTokensTable = &schema.Table{
		Name:       "mcp_tokens",
		Columns:    McpTokensColumns,
		PrimaryKey: []*schema.Column{McpTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mcptoken_token_hash",
				Unique:  true,
				Columns: []*schema.Column{McpTokensColumns[2]},
			},
			{
				Name:    "mcptoken_enabled",
				Unique:  false,
				Columns: []*schema.Column{McpTokensColumns[4]},
			},
		},
	}
	// UpstreamProvidersColumns holds the columns for the "upstream_providers" table.
	UpstreamProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 120},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 180},
		{Name: "app_id", Type: field.TypeString, Size: 180},
		{Name: "deploy_id", Type: field.TypeString, Nullable: true, Size: 180},
		{Name: "app_title", Type: field.TypeString, Nullable: true, Size: 180},
		{Name: "resource_id", Type: field.TypeString, Nullable: true, Size: 80},
		{Name: "endpoint", Type: field.TypeString, Size: 240, Default: "/mcp"},
		{Name: "transport", Type: field.TypeEnum, Enums: []string{"streamable_http", "sse"}, Default: "streamable_http"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UpstreamProvidersTable holds the schema information for the "upstream_providers" table.
	UpstreamProvidersTable = &schema.Table{
		Name:       "upstream_providers",
		Columns:    UpstreamProvidersColumns,
		PrimaryKey: []*schema.Column{UpstreamProvidersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "upstreamprovider_slug",
				Unique:  true,
				Columns: []*schema.Column{UpstreamProvidersColumns[2]},
			},
			{
				Name:    "upstreamprovider_app_id",
				Unique:  false,
				Columns: []*schema.Column{UpstreamProvidersColumns[3]},
			},
			{
				Name:    "upstreamprovider_enabled",
				Unique:  false,
				Columns: []*schema.Column{UpstreamProvidersColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		McpTokensTable,
		UpstreamProvidersTable,
	}
)

func init() {
}
