// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// McpCallLogsColumns holds the columns for the "mcp_call_logs" table.
	McpCallLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"local", "upstream"}, Default: "local"},
		{Name: "transport", Type: field.TypeEnum, Enums: []string{"streamable_http", "sse", "http"}, Default: "streamable_http"},
		{Name: "method", Type: field.TypeString, Size: 180},
		{Name: "target", Type: field.TypeString, Size: 240},
		{Name: "provider_slug", Type: field.TypeString, Nullable: true, Size: 180},
		{Name: "token_prefix", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "session_id", Type: field.TypeString, Nullable: true, Size: 180},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Size: 120},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "error"}, Default: "success"},
		{Name: "status_code", Type: field.TypeInt, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "created_at", Type: field.TypeTime},
	}
	// McpCallLogsTable holds the schema information for the "mcp_call_logs" table.
	McpCallLogsTable = &schema.Table{
		Name:       "mcp_call_logs",
		Columns:    McpCallLogsColumns,
		PrimaryKey: []*schema.Column{McpCallLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mcpcalllog_created_at",
				Unique:  false,
				Columns: []*schema.Column{McpCallLogsColumns[13]},
			},
			{
				Name:    "mcpcalllog_source",
				Unique:  false,
				Columns: []*schema.Column{McpCallLogsColumns[1]},
			},
			{
				Name:    "mcpcalllog_status",
				Unique:  false,
				Columns: []*schema.Column{McpCallLogsColumns[9]},
			},
			{
				Name:    "mcpcalllog_provider_slug",
				Unique:  false,
				Columns: []*schema.Column{McpCallLogsColumns[5]},
			},
		},
	}
	// McpTokensColumns holds the columns for the "mcp_tokens" table.
	McpTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 80},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "prefix", Type: field.TypeString, Size: 16},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// McpTokensTable holds the schema information for the "mcp_tokens" table.
	McpTokensTable = &schema.Table{
		Name:       "mcp_tokens",
		Columns:    McpTokensColumns,
		PrimaryKey: []*schema.Column{McpTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mcptoken_token_hash",
				Unique:  true,
				Columns: []*schema.Column{McpTokensColumns[2]},
			},
			{
				Name:    "mcptoken_enabled",
				Unique:  false,
				Columns: []*schema.Column{McpTokensColumns[4]},
			},
		},
	}
	// UpstreamProvidersColumns holds the columns for the "upstream_providers" table.
	UpstreamProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 120},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 300},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 180},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"lazycat", "custom"}, Default: "lazycat"},
		{Name: "app_id", Type: field.TypeString, Size: 180, Default: ""},
		{Name: "deploy_id", Type: field.TypeString, Nullable: true, Size: 180},
		{Name: "app_title", Type: field.TypeString, Nullable: true, Size: 180},
		{Name: "resource_id", Type: field.TypeString, Nullable: true, Size: 80},
		{Name: "base_url", Type: field.TypeString, Nullable: true, Size: 2048},
		{Name: "endpoint", Type: field.TypeString, Size: 240, Default: "/mcp"},
		{Name: "headers", Type: field.TypeString, Size: 2147483647, Default: "[]"},
		{Name: "transport", Type: field.TypeEnum, Enums: []string{"streamable_http", "sse"}, Default: "streamable_http"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UpstreamProvidersTable holds the schema information for the "upstream_providers" table.
	UpstreamProvidersTable = &schema.Table{
		Name:       "upstream_providers",
		Columns:    UpstreamProvidersColumns,
		PrimaryKey: []*schema.Column{UpstreamProvidersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "upstreamprovider_slug",
				Unique:  true,
				Columns: []*schema.Column{UpstreamProvidersColumns[3]},
			},
			{
				Name:    "upstreamprovider_type",
				Unique:  false,
				Columns: []*schema.Column{UpstreamProvidersColumns[4]},
			},
			{
				Name:    "upstreamprovider_app_id",
				Unique:  false,
				Columns: []*schema.Column{UpstreamProvidersColumns[5]},
			},
			{
				Name:    "upstreamprovider_enabled",
				Unique:  false,
				Columns: []*schema.Column{UpstreamProvidersColumns[13]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		McpCallLogsTable,
		McpTokensTable,
		UpstreamProvidersTable,
	}
)

func init() {
}
