// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"lazycat-mcp/ent/migrate"

	"lazycat-mcp/ent/mcptoken"
	"lazycat-mcp/ent/upstreamprovider"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MCPToken is the client for interacting with the MCPToken builders.
	MCPToken *MCPTokenClient
	// UpstreamProvider is the client for interacting with the UpstreamProvider builders.
	UpstreamProvider *UpstreamProviderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MCPToken = NewMCPTokenClient(c.config)
	c.UpstreamProvider = NewUpstreamProviderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		MCPToken:         NewMCPTokenClient(cfg),
		UpstreamProvider: NewUpstreamProviderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		MCPToken:         NewMCPTokenClient(cfg),
		UpstreamProvider: NewUpstreamProviderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MCPToken.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MCPToken.Use(hooks...)
	c.UpstreamProvider.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.MCPToken.Intercept(interceptors...)
	c.UpstreamProvider.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *MCPTokenMutation:
		return c.MCPToken.mutate(ctx, m)
	case *UpstreamProviderMutation:
		return c.UpstreamProvider.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// MCPTokenClient is a client for the MCPToken schema.
type MCPTokenClient struct {
	config
}

// NewMCPTokenClient returns a client for the MCPToken from the given config.
func NewMCPTokenClient(c config) *MCPTokenClient {
	return &MCPTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mcptoken.Hooks(f(g(h())))`.
func (c *MCPTokenClient) Use(hooks ...Hook) {
	c.hooks.MCPToken = append(c.hooks.MCPToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mcptoken.Intercept(f(g(h())))`.
func (c *MCPTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.MCPToken = append(c.inters.MCPToken, interceptors...)
}

// Create returns a builder for creating a MCPToken entity.
func (c *MCPTokenClient) Create() *MCPTokenCreate {
	mutation := newMCPTokenMutation(c.config, OpCreate)
	return &MCPTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MCPToken entities.
func (c *MCPTokenClient) CreateBulk(builders ...*MCPTokenCreate) *MCPTokenCreateBulk {
	return &MCPTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MCPTokenClient) MapCreateBulk(slice any, setFunc func(*MCPTokenCreate, int)) *MCPTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MCPTokenCreateBulk{err: fmt.Errorf("calling to MCPTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MCPTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MCPTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MCPToken.
func (c *MCPTokenClient) Update() *MCPTokenUpdate {
	mutation := newMCPTokenMutation(c.config, OpUpdate)
	return &MCPTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MCPTokenClient) UpdateOne(_m *MCPToken) *MCPTokenUpdateOne {
	mutation := newMCPTokenMutation(c.config, OpUpdateOne, withMCPToken(_m))
	return &MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MCPTokenClient) UpdateOneID(id int) *MCPTokenUpdateOne {
	mutation := newMCPTokenMutation(c.config, OpUpdateOne, withMCPTokenID(id))
	return &MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MCPToken.
func (c *MCPTokenClient) Delete() *MCPTokenDelete {
	mutation := newMCPTokenMutation(c.config, OpDelete)
	return &MCPTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MCPTokenClient) DeleteOne(_m *MCPToken) *MCPTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MCPTokenClient) DeleteOneID(id int) *MCPTokenDeleteOne {
	builder := c.Delete().Where(mcptoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MCPTokenDeleteOne{builder}
}

// Query returns a query builder for MCPToken.
func (c *MCPTokenClient) Query() *MCPTokenQuery {
	return &MCPTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMCPToken},
		inters: c.Interceptors(),
	}
}

// Get returns a MCPToken entity by its id.
func (c *MCPTokenClient) Get(ctx context.Context, id int) (*MCPToken, error) {
	return c.Query().Where(mcptoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MCPTokenClient) GetX(ctx context.Context, id int) *MCPToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MCPTokenClient) Hooks() []Hook {
	return c.hooks.MCPToken
}

// Interceptors returns the client interceptors.
func (c *MCPTokenClient) Interceptors() []Interceptor {
	return c.inters.MCPToken
}

func (c *MCPTokenClient) mutate(ctx context.Context, m *MCPTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MCPTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MCPTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MCPTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MCPTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MCPToken mutation op: %q", m.Op())
	}
}

// UpstreamProviderClient is a client for the UpstreamProvider schema.
type UpstreamProviderClient struct {
	config
}

// NewUpstreamProviderClient returns a client for the UpstreamProvider from the given config.
func NewUpstreamProviderClient(c config) *UpstreamProviderClient {
	return &UpstreamProviderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `upstreamprovider.Hooks(f(g(h())))`.
func (c *UpstreamProviderClient) Use(hooks ...Hook) {
	c.hooks.UpstreamProvider = append(c.hooks.UpstreamProvider, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `upstreamprovider.Intercept(f(g(h())))`.
func (c *UpstreamProviderClient) Intercept(interceptors ...Interceptor) {
	c.inters.UpstreamProvider = append(c.inters.UpstreamProvider, interceptors...)
}

// Create returns a builder for creating a UpstreamProvider entity.
func (c *UpstreamProviderClient) Create() *UpstreamProviderCreate {
	mutation := newUpstreamProviderMutation(c.config, OpCreate)
	return &UpstreamProviderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UpstreamProvider entities.
func (c *UpstreamProviderClient) CreateBulk(builders ...*UpstreamProviderCreate) *UpstreamProviderCreateBulk {
	return &UpstreamProviderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UpstreamProviderClient) MapCreateBulk(slice any, setFunc func(*UpstreamProviderCreate, int)) *UpstreamProviderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UpstreamProviderCreateBulk{err: fmt.Errorf("calling to UpstreamProviderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UpstreamProviderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UpstreamProviderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UpstreamProvider.
func (c *UpstreamProviderClient) Update() *UpstreamProviderUpdate {
	mutation := newUpstreamProviderMutation(c.config, OpUpdate)
	return &UpstreamProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UpstreamProviderClient) UpdateOne(_m *UpstreamProvider) *UpstreamProviderUpdateOne {
	mutation := newUpstreamProviderMutation(c.config, OpUpdateOne, withUpstreamProvider(_m))
	return &UpstreamProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UpstreamProviderClient) UpdateOneID(id int) *UpstreamProviderUpdateOne {
	mutation := newUpstreamProviderMutation(c.config, OpUpdateOne, withUpstreamProviderID(id))
	return &UpstreamProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UpstreamProvider.
func (c *UpstreamProviderClient) Delete() *UpstreamProviderDelete {
	mutation := newUpstreamProviderMutation(c.config, OpDelete)
	return &UpstreamProviderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UpstreamProviderClient) DeleteOne(_m *UpstreamProvider) *UpstreamProviderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UpstreamProviderClient) DeleteOneID(id int) *UpstreamProviderDeleteOne {
	builder := c.Delete().Where(upstreamprovider.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UpstreamProviderDeleteOne{builder}
}

// Query returns a query builder for UpstreamProvider.
func (c *UpstreamProviderClient) Query() *UpstreamProviderQuery {
	return &UpstreamProviderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUpstreamProvider},
		inters: c.Interceptors(),
	}
}

// Get returns a UpstreamProvider entity by its id.
func (c *UpstreamProviderClient) Get(ctx context.Context, id int) (*UpstreamProvider, error) {
	return c.Query().Where(upstreamprovider.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UpstreamProviderClient) GetX(ctx context.Context, id int) *UpstreamProvider {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UpstreamProviderClient) Hooks() []Hook {
	return c.hooks.UpstreamProvider
}

// Interceptors returns the client interceptors.
func (c *UpstreamProviderClient) Interceptors() []Interceptor {
	return c.inters.UpstreamProvider
}

func (c *UpstreamProviderClient) mutate(ctx context.Context, m *UpstreamProviderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UpstreamProviderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UpstreamProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UpstreamProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UpstreamProviderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UpstreamProvider mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		MCPToken, UpstreamProvider []ent.Hook
	}
	inters struct {
		MCPToken, UpstreamProvider []ent.Interceptor
	}
)
