// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lazycat-mcp/ent/mcpcalllog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MCPCallLog is the model entity for the MCPCallLog schema.
type MCPCallLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Source holds the value of the "source" field.
	Source mcpcalllog.Source `json:"source,omitempty"`
	// Transport holds the value of the "transport" field.
	Transport mcpcalllog.Transport `json:"transport,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// ProviderSlug holds the value of the "provider_slug" field.
	ProviderSlug *string `json:"provider_slug,omitempty"`
	// TokenPrefix holds the value of the "token_prefix" field.
	TokenPrefix *string `json:"token_prefix,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID *string `json:"session_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// Status holds the value of the "status" field.
	Status mcpcalllog.Status `json:"status,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode *int `json:"status_code,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MCPCallLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mcpcalllog.FieldID, mcpcalllog.FieldStatusCode, mcpcalllog.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case mcpcalllog.FieldSource, mcpcalllog.FieldTransport, mcpcalllog.FieldMethod, mcpcalllog.FieldTarget, mcpcalllog.FieldProviderSlug, mcpcalllog.FieldTokenPrefix, mcpcalllog.FieldSessionID, mcpcalllog.FieldRequestID, mcpcalllog.FieldStatus, mcpcalllog.FieldError:
			values[i] = new(sql.NullString)
		case mcpcalllog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MCPCallLog fields.
func (_m *MCPCallLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mcpcalllog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mcpcalllog.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = mcpcalllog.Source(value.String)
			}
		case mcpcalllog.FieldTransport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transport", values[i])
			} else if value.Valid {
				_m.Transport = mcpcalllog.Transport(value.String)
			}
		case mcpcalllog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case mcpcalllog.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case mcpcalllog.FieldProviderSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_slug", values[i])
			} else if value.Valid {
				_m.ProviderSlug = new(string)
				*_m.ProviderSlug = value.String
			}
		case mcpcalllog.FieldTokenPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_prefix", values[i])
			} else if value.Valid {
				_m.TokenPrefix = new(string)
				*_m.TokenPrefix = value.String
			}
		case mcpcalllog.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = new(string)
				*_m.SessionID = value.String
			}
		case mcpcalllog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case mcpcalllog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = mcpcalllog.Status(value.String)
			}
		case mcpcalllog.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = new(int)
				*_m.StatusCode = int(value.Int64)
			}
		case mcpcalllog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case mcpcalllog.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case mcpcalllog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MCPCallLog.
// This includes values selected through modifiers, order, etc.
func (_m *MCPCallLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MCPCallLog.
// Note that you need to call MCPCallLog.Unwrap() before calling this method if this MCPCallLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MCPCallLog) Update() *MCPCallLogUpdateOne {
	return NewMCPCallLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MCPCallLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MCPCallLog) Unwrap() *MCPCallLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MCPCallLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MCPCallLog) String() string {
	var builder strings.Builder
	builder.WriteString("MCPCallLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("transport=")
	builder.WriteString(fmt.Sprintf("%v", _m.Transport))
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	if v := _m.ProviderSlug; v != nil {
		builder.WriteString("provider_slug=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokenPrefix; v != nil {
		builder.WriteString("token_prefix=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SessionID; v != nil {
		builder.WriteString("session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.StatusCode; v != nil {
		builder.WriteString("status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MCPCallLogs is a parsable slice of MCPCallLog.
type MCPCallLogs []*MCPCallLog
