// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lazycat-mcp/ent/mcpcalllog"
	"lazycat-mcp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MCPCallLogUpdate is the builder for updating MCPCallLog entities.
type MCPCallLogUpdate struct {
	config
	hooks    []Hook
	mutation *MCPCallLogMutation
}

// Where appends a list predicates to the MCPCallLogUpdate builder.
func (_u *MCPCallLogUpdate) Where(ps ...predicate.MCPCallLog) *MCPCallLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *MCPCallLogUpdate) SetSource(v mcpcalllog.Source) *MCPCallLogUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableSource(v *mcpcalllog.Source) *MCPCallLogUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *MCPCallLogUpdate) SetTransport(v mcpcalllog.Transport) *MCPCallLogUpdate {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableTransport(v *mcpcalllog.Transport) *MCPCallLogUpdate {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *MCPCallLogUpdate) SetMethod(v string) *MCPCallLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableMethod(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *MCPCallLogUpdate) SetTarget(v string) *MCPCallLogUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableTarget(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetProviderSlug sets the "provider_slug" field.
func (_u *MCPCallLogUpdate) SetProviderSlug(v string) *MCPCallLogUpdate {
	_u.mutation.SetProviderSlug(v)
	return _u
}

// SetNillableProviderSlug sets the "provider_slug" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableProviderSlug(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetProviderSlug(*v)
	}
	return _u
}

// ClearProviderSlug clears the value of the "provider_slug" field.
func (_u *MCPCallLogUpdate) ClearProviderSlug() *MCPCallLogUpdate {
	_u.mutation.ClearProviderSlug()
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *MCPCallLogUpdate) SetTokenPrefix(v string) *MCPCallLogUpdate {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableTokenPrefix(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (_u *MCPCallLogUpdate) ClearTokenPrefix() *MCPCallLogUpdate {
	_u.mutation.ClearTokenPrefix()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MCPCallLogUpdate) SetSessionID(v string) *MCPCallLogUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableSessionID(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *MCPCallLogUpdate) ClearSessionID() *MCPCallLogUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *MCPCallLogUpdate) SetRequestID(v string) *MCPCallLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableRequestID(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *MCPCallLogUpdate) ClearRequestID() *MCPCallLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MCPCallLogUpdate) SetStatus(v mcpcalllog.Status) *MCPCallLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableStatus(v *mcpcalllog.Status) *MCPCallLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *MCPCallLogUpdate) SetStatusCode(v int) *MCPCallLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableStatusCode(v *int) *MCPCallLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *MCPCallLogUpdate) AddStatusCode(v int) *MCPCallLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *MCPCallLogUpdate) ClearStatusCode() *MCPCallLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *MCPCallLogUpdate) SetDurationMs(v int64) *MCPCallLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableDurationMs(v *int64) *MCPCallLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *MCPCallLogUpdate) AddDurationMs(v int64) *MCPCallLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetError sets the "error" field.
func (_u *MCPCallLogUpdate) SetError(v string) *MCPCallLogUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *MCPCallLogUpdate) SetNillableError(v *string) *MCPCallLogUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *MCPCallLogUpdate) ClearError() *MCPCallLogUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the MCPCallLogMutation object of the builder.
func (_u *MCPCallLogUpdate) Mutation() *MCPCallLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MCPCallLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPCallLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MCPCallLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPCallLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPCallLogUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := mcpcalllog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := mcpcalllog.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.transport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := mcpcalllog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := mcpcalllog.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSlug(); ok {
		if err := mcpcalllog.ProviderSlugValidator(v); err != nil {
			return &ValidationError{Name: "provider_slug", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.provider_slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := mcpcalllog.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.token_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := mcpcalllog.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := mcpcalllog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mcpcalllog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusCode(); ok {
		if err := mcpcalllog.StatusCodeValidator(v); err != nil {
			return &ValidationError{Name: "status_code", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.status_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := mcpcalllog.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.duration_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Error(); ok {
		if err := mcpcalllog.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.error": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPCallLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpcalllog.Table, mcpcalllog.Columns, sqlgraph.NewFieldSpec(mcpcalllog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(mcpcalllog.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(mcpcalllog.FieldTransport, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(mcpcalllog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(mcpcalllog.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSlug(); ok {
		_spec.SetField(mcpcalllog.FieldProviderSlug, field.TypeString, value)
	}
	if _u.mutation.ProviderSlugCleared() {
		_spec.ClearField(mcpcalllog.FieldProviderSlug, field.TypeString)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(mcpcalllog.FieldTokenPrefix, field.TypeString, value)
	}
	if _u.mutation.TokenPrefixCleared() {
		_spec.ClearField(mcpcalllog.FieldTokenPrefix, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(mcpcalllog.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(mcpcalllog.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(mcpcalllog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(mcpcalllog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mcpcalllog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(mcpcalllog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(mcpcalllog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(mcpcalllog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(mcpcalllog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(mcpcalllog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(mcpcalllog.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(mcpcalllog.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpcalllog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MCPCallLogUpdateOne is the builder for updating a single MCPCallLog entity.
type MCPCallLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MCPCallLogMutation
}

// SetSource sets the "source" field.
func (_u *MCPCallLogUpdateOne) SetSource(v mcpcalllog.Source) *MCPCallLogUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableSource(v *mcpcalllog.Source) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *MCPCallLogUpdateOne) SetTransport(v mcpcalllog.Transport) *MCPCallLogUpdateOne {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableTransport(v *mcpcalllog.Transport) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *MCPCallLogUpdateOne) SetMethod(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableMethod(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *MCPCallLogUpdateOne) SetTarget(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableTarget(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetProviderSlug sets the "provider_slug" field.
func (_u *MCPCallLogUpdateOne) SetProviderSlug(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetProviderSlug(v)
	return _u
}

// SetNillableProviderSlug sets the "provider_slug" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableProviderSlug(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetProviderSlug(*v)
	}
	return _u
}

// ClearProviderSlug clears the value of the "provider_slug" field.
func (_u *MCPCallLogUpdateOne) ClearProviderSlug() *MCPCallLogUpdateOne {
	_u.mutation.ClearProviderSlug()
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *MCPCallLogUpdateOne) SetTokenPrefix(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableTokenPrefix(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (_u *MCPCallLogUpdateOne) ClearTokenPrefix() *MCPCallLogUpdateOne {
	_u.mutation.ClearTokenPrefix()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MCPCallLogUpdateOne) SetSessionID(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableSessionID(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *MCPCallLogUpdateOne) ClearSessionID() *MCPCallLogUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *MCPCallLogUpdateOne) SetRequestID(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableRequestID(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *MCPCallLogUpdateOne) ClearRequestID() *MCPCallLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MCPCallLogUpdateOne) SetStatus(v mcpcalllog.Status) *MCPCallLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableStatus(v *mcpcalllog.Status) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *MCPCallLogUpdateOne) SetStatusCode(v int) *MCPCallLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableStatusCode(v *int) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *MCPCallLogUpdateOne) AddStatusCode(v int) *MCPCallLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *MCPCallLogUpdateOne) ClearStatusCode() *MCPCallLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *MCPCallLogUpdateOne) SetDurationMs(v int64) *MCPCallLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableDurationMs(v *int64) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *MCPCallLogUpdateOne) AddDurationMs(v int64) *MCPCallLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetError sets the "error" field.
func (_u *MCPCallLogUpdateOne) SetError(v string) *MCPCallLogUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *MCPCallLogUpdateOne) SetNillableError(v *string) *MCPCallLogUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *MCPCallLogUpdateOne) ClearError() *MCPCallLogUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the MCPCallLogMutation object of the builder.
func (_u *MCPCallLogUpdateOne) Mutation() *MCPCallLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the MCPCallLogUpdate builder.
func (_u *MCPCallLogUpdateOne) Where(ps ...predicate.MCPCallLog) *MCPCallLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MCPCallLogUpdateOne) Select(field string, fields ...string) *MCPCallLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MCPCallLog entity.
func (_u *MCPCallLogUpdateOne) Save(ctx context.Context) (*MCPCallLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPCallLogUpdateOne) SaveX(ctx context.Context) *MCPCallLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MCPCallLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPCallLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPCallLogUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := mcpcalllog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := mcpcalllog.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.transport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := mcpcalllog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Target(); ok {
		if err := mcpcalllog.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSlug(); ok {
		if err := mcpcalllog.ProviderSlugValidator(v); err != nil {
			return &ValidationError{Name: "provider_slug", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.provider_slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := mcpcalllog.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.token_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := mcpcalllog.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := mcpcalllog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mcpcalllog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusCode(); ok {
		if err := mcpcalllog.StatusCodeValidator(v); err != nil {
			return &ValidationError{Name: "status_code", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.status_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := mcpcalllog.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.duration_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Error(); ok {
		if err := mcpcalllog.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.error": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPCallLogUpdateOne) sqlSave(ctx context.Context) (_node *MCPCallLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpcalllog.Table, mcpcalllog.Columns, sqlgraph.NewFieldSpec(mcpcalllog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MCPCallLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpcalllog.FieldID)
		for _, f := range fields {
			if !mcpcalllog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcpcalllog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(mcpcalllog.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(mcpcalllog.FieldTransport, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(mcpcalllog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(mcpcalllog.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSlug(); ok {
		_spec.SetField(mcpcalllog.FieldProviderSlug, field.TypeString, value)
	}
	if _u.mutation.ProviderSlugCleared() {
		_spec.ClearField(mcpcalllog.FieldProviderSlug, field.TypeString)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(mcpcalllog.FieldTokenPrefix, field.TypeString, value)
	}
	if _u.mutation.TokenPrefixCleared() {
		_spec.ClearField(mcpcalllog.FieldTokenPrefix, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(mcpcalllog.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(mcpcalllog.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(mcpcalllog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(mcpcalllog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mcpcalllog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(mcpcalllog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(mcpcalllog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(mcpcalllog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(mcpcalllog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(mcpcalllog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(mcpcalllog.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(mcpcalllog.FieldError, field.TypeString)
	}
	_node = &MCPCallLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpcalllog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
