// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lazycat-mcp/ent/mcpcalllog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MCPCallLogCreate is the builder for creating a MCPCallLog entity.
type MCPCallLogCreate struct {
	config
	mutation *MCPCallLogMutation
	hooks    []Hook
}

// SetSource sets the "source" field.
func (_c *MCPCallLogCreate) SetSource(v mcpcalllog.Source) *MCPCallLogCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableSource(v *mcpcalllog.Source) *MCPCallLogCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetTransport sets the "transport" field.
func (_c *MCPCallLogCreate) SetTransport(v mcpcalllog.Transport) *MCPCallLogCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableTransport(v *mcpcalllog.Transport) *MCPCallLogCreate {
	if v != nil {
		_c.SetTransport(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *MCPCallLogCreate) SetMethod(v string) *MCPCallLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *MCPCallLogCreate) SetTarget(v string) *MCPCallLogCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetProviderSlug sets the "provider_slug" field.
func (_c *MCPCallLogCreate) SetProviderSlug(v string) *MCPCallLogCreate {
	_c.mutation.SetProviderSlug(v)
	return _c
}

// SetNillableProviderSlug sets the "provider_slug" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableProviderSlug(v *string) *MCPCallLogCreate {
	if v != nil {
		_c.SetProviderSlug(*v)
	}
	return _c
}

// SetTokenPrefix sets the "token_prefix" field.
func (_c *MCPCallLogCreate) SetTokenPrefix(v string) *MCPCallLogCreate {
	_c.mutation.SetTokenPrefix(v)
	return _c
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableTokenPrefix(v *string) *MCPCallLogCreate {
	if v != nil {
		_c.SetTokenPrefix(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *MCPCallLogCreate) SetSessionID(v string) *MCPCallLogCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableSessionID(v *string) *MCPCallLogCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *MCPCallLogCreate) SetRequestID(v string) *MCPCallLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableRequestID(v *string) *MCPCallLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MCPCallLogCreate) SetStatus(v mcpcalllog.Status) *MCPCallLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableStatus(v *mcpcalllog.Status) *MCPCallLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *MCPCallLogCreate) SetStatusCode(v int) *MCPCallLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableStatusCode(v *int) *MCPCallLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *MCPCallLogCreate) SetDurationMs(v int64) *MCPCallLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableDurationMs(v *int64) *MCPCallLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *MCPCallLogCreate) SetError(v string) *MCPCallLogCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableError(v *string) *MCPCallLogCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MCPCallLogCreate) SetCreatedAt(v time.Time) *MCPCallLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MCPCallLogCreate) SetNillableCreatedAt(v *time.Time) *MCPCallLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the MCPCallLogMutation object of the builder.
func (_c *MCPCallLogCreate) Mutation() *MCPCallLogMutation {
	return _c.mutation
}

// Save creates the MCPCallLog in the database.
func (_c *MCPCallLogCreate) Save(ctx context.Context) (*MCPCallLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MCPCallLogCreate) SaveX(ctx context.Context) *MCPCallLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPCallLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPCallLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MCPCallLogCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := mcpcalllog.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Transport(); !ok {
		v := mcpcalllog.DefaultTransport
		_c.mutation.SetTransport(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mcpcalllog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := mcpcalllog.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mcpcalllog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MCPCallLogCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "MCPCallLog.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := mcpcalllog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Transport(); !ok {
		return &ValidationError{Name: "transport", err: errors.New(`ent: missing required field "MCPCallLog.transport"`)}
	}
	if v, ok := _c.mutation.Transport(); ok {
		if err := mcpcalllog.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.transport": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "MCPCallLog.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := mcpcalllog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "MCPCallLog.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := mcpcalllog.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.target": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderSlug(); ok {
		if err := mcpcalllog.ProviderSlugValidator(v); err != nil {
			return &ValidationError{Name: "provider_slug", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.provider_slug": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TokenPrefix(); ok {
		if err := mcpcalllog.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.token_prefix": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := mcpcalllog.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := mcpcalllog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MCPCallLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mcpcalllog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StatusCode(); ok {
		if err := mcpcalllog.StatusCodeValidator(v); err != nil {
			return &ValidationError{Name: "status_code", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.status_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "MCPCallLog.duration_ms"`)}
	}
	if v, ok := _c.mutation.DurationMs(); ok {
		if err := mcpcalllog.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.duration_ms": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Error(); ok {
		if err := mcpcalllog.ErrorValidator(v); err != nil {
			return &ValidationError{Name: "error", err: fmt.Errorf(`ent: validator failed for field "MCPCallLog.error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MCPCallLog.created_at"`)}
	}
	return nil
}

func (_c *MCPCallLogCreate) sqlSave(ctx context.Context) (*MCPCallLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MCPCallLogCreate) createSpec() (*MCPCallLog, *sqlgraph.CreateSpec) {
	var (
		_node = &MCPCallLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mcpcalllog.Table, sqlgraph.NewFieldSpec(mcpcalllog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(mcpcalllog.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(mcpcalllog.FieldTransport, field.TypeEnum, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(mcpcalllog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(mcpcalllog.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.ProviderSlug(); ok {
		_spec.SetField(mcpcalllog.FieldProviderSlug, field.TypeString, value)
		_node.ProviderSlug = &value
	}
	if value, ok := _c.mutation.TokenPrefix(); ok {
		_spec.SetField(mcpcalllog.FieldTokenPrefix, field.TypeString, value)
		_node.TokenPrefix = &value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(mcpcalllog.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(mcpcalllog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mcpcalllog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(mcpcalllog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(mcpcalllog.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(mcpcalllog.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mcpcalllog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MCPCallLogCreateBulk is the builder for creating many MCPCallLog entities in bulk.
type MCPCallLogCreateBulk struct {
	config
	err      error
	builders []*MCPCallLogCreate
}

// Save creates the MCPCallLog entities in the database.
func (_c *MCPCallLogCreateBulk) Save(ctx context.Context) ([]*MCPCallLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MCPCallLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MCPCallLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MCPCallLogCreateBulk) SaveX(ctx context.Context) []*MCPCallLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPCallLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPCallLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
