// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lazycat-mcp/ent/mcptoken"
	"lazycat-mcp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MCPTokenUpdate is the builder for updating MCPToken entities.
type MCPTokenUpdate struct {
	config
	hooks    []Hook
	mutation *MCPTokenMutation
}

// Where appends a list predicates to the MCPTokenUpdate builder.
func (_u *MCPTokenUpdate) Where(ps ...predicate.MCPToken) *MCPTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MCPTokenUpdate) SetName(v string) *MCPTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableName(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *MCPTokenUpdate) SetTokenHash(v string) *MCPTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableTokenHash(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *MCPTokenUpdate) SetPrefix(v string) *MCPTokenUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillablePrefix(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *MCPTokenUpdate) SetOwnerUserID(v string) *MCPTokenUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableOwnerUserID(v *string) *MCPTokenUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetOwnerIsAdmin sets the "owner_is_admin" field.
func (_u *MCPTokenUpdate) SetOwnerIsAdmin(v bool) *MCPTokenUpdate {
	_u.mutation.SetOwnerIsAdmin(v)
	return _u
}

// SetNillableOwnerIsAdmin sets the "owner_is_admin" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableOwnerIsAdmin(v *bool) *MCPTokenUpdate {
	if v != nil {
		_u.SetOwnerIsAdmin(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MCPTokenUpdate) SetEnabled(v bool) *MCPTokenUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableEnabled(v *bool) *MCPTokenUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MCPTokenUpdate) SetExpiresAt(v time.Time) *MCPTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableExpiresAt(v *time.Time) *MCPTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MCPTokenUpdate) ClearExpiresAt() *MCPTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *MCPTokenUpdate) SetLastUsedAt(v time.Time) *MCPTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *MCPTokenUpdate) SetNillableLastUsedAt(v *time.Time) *MCPTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *MCPTokenUpdate) ClearLastUsedAt() *MCPTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MCPTokenUpdate) SetUpdatedAt(v time.Time) *MCPTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MCPTokenMutation object of the builder.
func (_u *MCPTokenUpdate) Mutation() *MCPTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MCPTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MCPTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MCPTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcptoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPTokenUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mcptoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPToken.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := mcptoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prefix(); ok {
		if err := mcptoken.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "MCPToken.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := mcptoken.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "MCPToken.owner_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcptoken.Table, mcptoken.Columns, sqlgraph.NewFieldSpec(mcptoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcptoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(mcptoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(mcptoken.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(mcptoken.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerIsAdmin(); ok {
		_spec.SetField(mcptoken.FieldOwnerIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mcptoken.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mcptoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(mcptoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(mcptoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(mcptoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcptoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcptoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MCPTokenUpdateOne is the builder for updating a single MCPToken entity.
type MCPTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MCPTokenMutation
}

// SetName sets the "name" field.
func (_u *MCPTokenUpdateOne) SetName(v string) *MCPTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableName(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *MCPTokenUpdateOne) SetTokenHash(v string) *MCPTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableTokenHash(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *MCPTokenUpdateOne) SetPrefix(v string) *MCPTokenUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillablePrefix(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *MCPTokenUpdateOne) SetOwnerUserID(v string) *MCPTokenUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableOwnerUserID(v *string) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetOwnerIsAdmin sets the "owner_is_admin" field.
func (_u *MCPTokenUpdateOne) SetOwnerIsAdmin(v bool) *MCPTokenUpdateOne {
	_u.mutation.SetOwnerIsAdmin(v)
	return _u
}

// SetNillableOwnerIsAdmin sets the "owner_is_admin" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableOwnerIsAdmin(v *bool) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetOwnerIsAdmin(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MCPTokenUpdateOne) SetEnabled(v bool) *MCPTokenUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableEnabled(v *bool) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MCPTokenUpdateOne) SetExpiresAt(v time.Time) *MCPTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MCPTokenUpdateOne) ClearExpiresAt() *MCPTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *MCPTokenUpdateOne) SetLastUsedAt(v time.Time) *MCPTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *MCPTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *MCPTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *MCPTokenUpdateOne) ClearLastUsedAt() *MCPTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MCPTokenUpdateOne) SetUpdatedAt(v time.Time) *MCPTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MCPTokenMutation object of the builder.
func (_u *MCPTokenUpdateOne) Mutation() *MCPTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the MCPTokenUpdate builder.
func (_u *MCPTokenUpdateOne) Where(ps ...predicate.MCPToken) *MCPTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MCPTokenUpdateOne) Select(field string, fields ...string) *MCPTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MCPToken entity.
func (_u *MCPTokenUpdateOne) Save(ctx context.Context) (*MCPToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPTokenUpdateOne) SaveX(ctx context.Context) *MCPToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MCPTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MCPTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcptoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mcptoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPToken.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := mcptoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "MCPToken.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prefix(); ok {
		if err := mcptoken.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "MCPToken.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := mcptoken.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "MCPToken.owner_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPTokenUpdateOne) sqlSave(ctx context.Context) (_node *MCPToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcptoken.Table, mcptoken.Columns, sqlgraph.NewFieldSpec(mcptoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MCPToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcptoken.FieldID)
		for _, f := range fields {
			if !mcptoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcptoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcptoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(mcptoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(mcptoken.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(mcptoken.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerIsAdmin(); ok {
		_spec.SetField(mcptoken.FieldOwnerIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mcptoken.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mcptoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(mcptoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(mcptoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(mcptoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcptoken.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &MCPToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcptoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
