// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lazycat-mcp/ent/mcptoken"
	"lazycat-mcp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MCPTokenDelete is the builder for deleting a MCPToken entity.
type MCPTokenDelete struct {
	config
	hooks    []Hook
	mutation *MCPTokenMutation
}

// Where appends a list predicates to the MCPTokenDelete builder.
func (_d *MCPTokenDelete) Where(ps ...predicate.MCPToken) *MCPTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MCPTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MCPTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MCPTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mcptoken.Table, sqlgraph.NewFieldSpec(mcptoken.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MCPTokenDeleteOne is the builder for deleting a single MCPToken entity.
type MCPTokenDeleteOne struct {
	_d *MCPTokenDelete
}

// Where appends a list predicates to the MCPTokenDelete builder.
func (_d *MCPTokenDeleteOne) Where(ps ...predicate.MCPToken) *MCPTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MCPTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mcptoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MCPTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
