// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lazycat-mcp/ent/mcptoken"
	"lazycat-mcp/ent/predicate"
	"lazycat-mcp/ent/upstreamprovider"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMCPToken         = "MCPToken"
	TypeUpstreamProvider = "UpstreamProvider"
)

// MCPTokenMutation represents an operation that mutates the MCPToken nodes in the graph.
type MCPTokenMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	token_hash    *string
	prefix        *string
	enabled       *bool
	expires_at    *time.Time
	last_used_at  *time.Time
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MCPToken, error)
	predicates    []predicate.MCPToken
}

var _ ent.Mutation = (*MCPTokenMutation)(nil)

// mcptokenOption allows management of the mutation configuration using functional options.
type mcptokenOption func(*MCPTokenMutation)

// newMCPTokenMutation creates new mutation for the MCPToken entity.
func newMCPTokenMutation(c config, op Op, opts ...mcptokenOption) *MCPTokenMutation {
	m := &MCPTokenMutation{
		config:        c,
		op:            op,
		typ:           TypeMCPToken,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMCPTokenID sets the ID field of the mutation.
func withMCPTokenID(id int) mcptokenOption {
	return func(m *MCPTokenMutation) {
		var (
			err   error
			once  sync.Once
			value *MCPToken
		)
		m.oldValue = func(ctx context.Context) (*MCPToken, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MCPToken.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMCPToken sets the old MCPToken of the mutation.
func withMCPToken(node *MCPToken) mcptokenOption {
	return func(m *MCPTokenMutation) {
		m.oldValue = func(context.Context) (*MCPToken, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MCPTokenMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MCPTokenMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MCPTokenMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MCPTokenMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MCPToken.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *MCPTokenMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *MCPTokenMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *MCPTokenMutation) ResetName() {
	m.name = nil
}

// SetTokenHash sets the "token_hash" field.
func (m *MCPTokenMutation) SetTokenHash(s string) {
	m.token_hash = &s
}

// TokenHash returns the value of the "token_hash" field in the mutation.
func (m *MCPTokenMutation) TokenHash() (r string, exists bool) {
	v := m.token_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldTokenHash returns the old "token_hash" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldTokenHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTokenHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTokenHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTokenHash: %w", err)
	}
	return oldValue.TokenHash, nil
}

// ResetTokenHash resets all changes to the "token_hash" field.
func (m *MCPTokenMutation) ResetTokenHash() {
	m.token_hash = nil
}

// SetPrefix sets the "prefix" field.
func (m *MCPTokenMutation) SetPrefix(s string) {
	m.prefix = &s
}

// Prefix returns the value of the "prefix" field in the mutation.
func (m *MCPTokenMutation) Prefix() (r string, exists bool) {
	v := m.prefix
	if v == nil {
		return
	}
	return *v, true
}

// OldPrefix returns the old "prefix" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldPrefix(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrefix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrefix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrefix: %w", err)
	}
	return oldValue.Prefix, nil
}

// ResetPrefix resets all changes to the "prefix" field.
func (m *MCPTokenMutation) ResetPrefix() {
	m.prefix = nil
}

// SetEnabled sets the "enabled" field.
func (m *MCPTokenMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *MCPTokenMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *MCPTokenMutation) ResetEnabled() {
	m.enabled = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *MCPTokenMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *MCPTokenMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldExpiresAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (m *MCPTokenMutation) ClearExpiresAt() {
	m.expires_at = nil
	m.clearedFields[mcptoken.FieldExpiresAt] = struct{}{}
}

// ExpiresAtCleared returns if the "expires_at" field was cleared in this mutation.
func (m *MCPTokenMutation) ExpiresAtCleared() bool {
	_, ok := m.clearedFields[mcptoken.FieldExpiresAt]
	return ok
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *MCPTokenMutation) ResetExpiresAt() {
	m.expires_at = nil
	delete(m.clearedFields, mcptoken.FieldExpiresAt)
}

// SetLastUsedAt sets the "last_used_at" field.
func (m *MCPTokenMutation) SetLastUsedAt(t time.Time) {
	m.last_used_at = &t
}

// LastUsedAt returns the value of the "last_used_at" field in the mutation.
func (m *MCPTokenMutation) LastUsedAt() (r time.Time, exists bool) {
	v := m.last_used_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastUsedAt returns the old "last_used_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldLastUsedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastUsedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastUsedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastUsedAt: %w", err)
	}
	return oldValue.LastUsedAt, nil
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (m *MCPTokenMutation) ClearLastUsedAt() {
	m.last_used_at = nil
	m.clearedFields[mcptoken.FieldLastUsedAt] = struct{}{}
}

// LastUsedAtCleared returns if the "last_used_at" field was cleared in this mutation.
func (m *MCPTokenMutation) LastUsedAtCleared() bool {
	_, ok := m.clearedFields[mcptoken.FieldLastUsedAt]
	return ok
}

// ResetLastUsedAt resets all changes to the "last_used_at" field.
func (m *MCPTokenMutation) ResetLastUsedAt() {
	m.last_used_at = nil
	delete(m.clearedFields, mcptoken.FieldLastUsedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *MCPTokenMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *MCPTokenMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *MCPTokenMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *MCPTokenMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *MCPTokenMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the MCPToken entity.
// If the MCPToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MCPTokenMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *MCPTokenMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the MCPTokenMutation builder.
func (m *MCPTokenMutation) Where(ps ...predicate.MCPToken) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MCPTokenMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MCPTokenMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MCPToken, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MCPTokenMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MCPTokenMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MCPToken).
func (m *MCPTokenMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MCPTokenMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.name != nil {
		fields = append(fields, mcptoken.FieldName)
	}
	if m.token_hash != nil {
		fields = append(fields, mcptoken.FieldTokenHash)
	}
	if m.prefix != nil {
		fields = append(fields, mcptoken.FieldPrefix)
	}
	if m.enabled != nil {
		fields = append(fields, mcptoken.FieldEnabled)
	}
	if m.expires_at != nil {
		fields = append(fields, mcptoken.FieldExpiresAt)
	}
	if m.last_used_at != nil {
		fields = append(fields, mcptoken.FieldLastUsedAt)
	}
	if m.created_at != nil {
		fields = append(fields, mcptoken.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, mcptoken.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MCPTokenMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case mcptoken.FieldName:
		return m.Name()
	case mcptoken.FieldTokenHash:
		return m.TokenHash()
	case mcptoken.FieldPrefix:
		return m.Prefix()
	case mcptoken.FieldEnabled:
		return m.Enabled()
	case mcptoken.FieldExpiresAt:
		return m.ExpiresAt()
	case mcptoken.FieldLastUsedAt:
		return m.LastUsedAt()
	case mcptoken.FieldCreatedAt:
		return m.CreatedAt()
	case mcptoken.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MCPTokenMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case mcptoken.FieldName:
		return m.OldName(ctx)
	case mcptoken.FieldTokenHash:
		return m.OldTokenHash(ctx)
	case mcptoken.FieldPrefix:
		return m.OldPrefix(ctx)
	case mcptoken.FieldEnabled:
		return m.OldEnabled(ctx)
	case mcptoken.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case mcptoken.FieldLastUsedAt:
		return m.OldLastUsedAt(ctx)
	case mcptoken.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case mcptoken.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown MCPToken field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MCPTokenMutation) SetField(name string, value ent.Value) error {
	switch name {
	case mcptoken.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case mcptoken.FieldTokenHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTokenHash(v)
		return nil
	case mcptoken.FieldPrefix:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrefix(v)
		return nil
	case mcptoken.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case mcptoken.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case mcptoken.FieldLastUsedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastUsedAt(v)
		return nil
	case mcptoken.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case mcptoken.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown MCPToken field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MCPTokenMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MCPTokenMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MCPTokenMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown MCPToken numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MCPTokenMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(mcptoken.FieldExpiresAt) {
		fields = append(fields, mcptoken.FieldExpiresAt)
	}
	if m.FieldCleared(mcptoken.FieldLastUsedAt) {
		fields = append(fields, mcptoken.FieldLastUsedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MCPTokenMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MCPTokenMutation) ClearField(name string) error {
	switch name {
	case mcptoken.FieldExpiresAt:
		m.ClearExpiresAt()
		return nil
	case mcptoken.FieldLastUsedAt:
		m.ClearLastUsedAt()
		return nil
	}
	return fmt.Errorf("unknown MCPToken nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MCPTokenMutation) ResetField(name string) error {
	switch name {
	case mcptoken.FieldName:
		m.ResetName()
		return nil
	case mcptoken.FieldTokenHash:
		m.ResetTokenHash()
		return nil
	case mcptoken.FieldPrefix:
		m.ResetPrefix()
		return nil
	case mcptoken.FieldEnabled:
		m.ResetEnabled()
		return nil
	case mcptoken.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case mcptoken.FieldLastUsedAt:
		m.ResetLastUsedAt()
		return nil
	case mcptoken.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case mcptoken.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown MCPToken field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MCPTokenMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MCPTokenMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MCPTokenMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MCPTokenMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MCPTokenMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MCPTokenMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MCPTokenMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MCPToken unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MCPTokenMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MCPToken edge %s", name)
}

// UpstreamProviderMutation represents an operation that mutates the UpstreamProvider nodes in the graph.
type UpstreamProviderMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	slug          *string
	app_id        *string
	deploy_id     *string
	app_title     *string
	resource_id   *string
	endpoint      *string
	transport     *upstreamprovider.Transport
	enabled       *bool
	last_used_at  *time.Time
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UpstreamProvider, error)
	predicates    []predicate.UpstreamProvider
}

var _ ent.Mutation = (*UpstreamProviderMutation)(nil)

// upstreamproviderOption allows management of the mutation configuration using functional options.
type upstreamproviderOption func(*UpstreamProviderMutation)

// newUpstreamProviderMutation creates new mutation for the UpstreamProvider entity.
func newUpstreamProviderMutation(c config, op Op, opts ...upstreamproviderOption) *UpstreamProviderMutation {
	m := &UpstreamProviderMutation{
		config:        c,
		op:            op,
		typ:           TypeUpstreamProvider,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUpstreamProviderID sets the ID field of the mutation.
func withUpstreamProviderID(id int) upstreamproviderOption {
	return func(m *UpstreamProviderMutation) {
		var (
			err   error
			once  sync.Once
			value *UpstreamProvider
		)
		m.oldValue = func(ctx context.Context) (*UpstreamProvider, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UpstreamProvider.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUpstreamProvider sets the old UpstreamProvider of the mutation.
func withUpstreamProvider(node *UpstreamProvider) upstreamproviderOption {
	return func(m *UpstreamProviderMutation) {
		m.oldValue = func(context.Context) (*UpstreamProvider, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UpstreamProviderMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UpstreamProviderMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UpstreamProviderMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UpstreamProviderMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UpstreamProvider.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *UpstreamProviderMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UpstreamProviderMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UpstreamProviderMutation) ResetName() {
	m.name = nil
}

// SetSlug sets the "slug" field.
func (m *UpstreamProviderMutation) SetSlug(s string) {
	m.slug = &s
}

// Slug returns the value of the "slug" field in the mutation.
func (m *UpstreamProviderMutation) Slug() (r string, exists bool) {
	v := m.slug
	if v == nil {
		return
	}
	return *v, true
}

// OldSlug returns the old "slug" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldSlug(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSlug is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSlug requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSlug: %w", err)
	}
	return oldValue.Slug, nil
}

// ResetSlug resets all changes to the "slug" field.
func (m *UpstreamProviderMutation) ResetSlug() {
	m.slug = nil
}

// SetAppID sets the "app_id" field.
func (m *UpstreamProviderMutation) SetAppID(s string) {
	m.app_id = &s
}

// AppID returns the value of the "app_id" field in the mutation.
func (m *UpstreamProviderMutation) AppID() (r string, exists bool) {
	v := m.app_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAppID returns the old "app_id" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldAppID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppID: %w", err)
	}
	return oldValue.AppID, nil
}

// ResetAppID resets all changes to the "app_id" field.
func (m *UpstreamProviderMutation) ResetAppID() {
	m.app_id = nil
}

// SetDeployID sets the "deploy_id" field.
func (m *UpstreamProviderMutation) SetDeployID(s string) {
	m.deploy_id = &s
}

// DeployID returns the value of the "deploy_id" field in the mutation.
func (m *UpstreamProviderMutation) DeployID() (r string, exists bool) {
	v := m.deploy_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDeployID returns the old "deploy_id" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldDeployID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeployID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeployID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeployID: %w", err)
	}
	return oldValue.DeployID, nil
}

// ClearDeployID clears the value of the "deploy_id" field.
func (m *UpstreamProviderMutation) ClearDeployID() {
	m.deploy_id = nil
	m.clearedFields[upstreamprovider.FieldDeployID] = struct{}{}
}

// DeployIDCleared returns if the "deploy_id" field was cleared in this mutation.
func (m *UpstreamProviderMutation) DeployIDCleared() bool {
	_, ok := m.clearedFields[upstreamprovider.FieldDeployID]
	return ok
}

// ResetDeployID resets all changes to the "deploy_id" field.
func (m *UpstreamProviderMutation) ResetDeployID() {
	m.deploy_id = nil
	delete(m.clearedFields, upstreamprovider.FieldDeployID)
}

// SetAppTitle sets the "app_title" field.
func (m *UpstreamProviderMutation) SetAppTitle(s string) {
	m.app_title = &s
}

// AppTitle returns the value of the "app_title" field in the mutation.
func (m *UpstreamProviderMutation) AppTitle() (r string, exists bool) {
	v := m.app_title
	if v == nil {
		return
	}
	return *v, true
}

// OldAppTitle returns the old "app_title" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldAppTitle(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAppTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAppTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAppTitle: %w", err)
	}
	return oldValue.AppTitle, nil
}

// ClearAppTitle clears the value of the "app_title" field.
func (m *UpstreamProviderMutation) ClearAppTitle() {
	m.app_title = nil
	m.clearedFields[upstreamprovider.FieldAppTitle] = struct{}{}
}

// AppTitleCleared returns if the "app_title" field was cleared in this mutation.
func (m *UpstreamProviderMutation) AppTitleCleared() bool {
	_, ok := m.clearedFields[upstreamprovider.FieldAppTitle]
	return ok
}

// ResetAppTitle resets all changes to the "app_title" field.
func (m *UpstreamProviderMutation) ResetAppTitle() {
	m.app_title = nil
	delete(m.clearedFields, upstreamprovider.FieldAppTitle)
}

// SetResourceID sets the "resource_id" field.
func (m *UpstreamProviderMutation) SetResourceID(s string) {
	m.resource_id = &s
}

// ResourceID returns the value of the "resource_id" field in the mutation.
func (m *UpstreamProviderMutation) ResourceID() (r string, exists bool) {
	v := m.resource_id
	if v == nil {
		return
	}
	return *v, true
}

// OldResourceID returns the old "resource_id" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldResourceID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResourceID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResourceID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResourceID: %w", err)
	}
	return oldValue.ResourceID, nil
}

// ClearResourceID clears the value of the "resource_id" field.
func (m *UpstreamProviderMutation) ClearResourceID() {
	m.resource_id = nil
	m.clearedFields[upstreamprovider.FieldResourceID] = struct{}{}
}

// ResourceIDCleared returns if the "resource_id" field was cleared in this mutation.
func (m *UpstreamProviderMutation) ResourceIDCleared() bool {
	_, ok := m.clearedFields[upstreamprovider.FieldResourceID]
	return ok
}

// ResetResourceID resets all changes to the "resource_id" field.
func (m *UpstreamProviderMutation) ResetResourceID() {
	m.resource_id = nil
	delete(m.clearedFields, upstreamprovider.FieldResourceID)
}

// SetEndpoint sets the "endpoint" field.
func (m *UpstreamProviderMutation) SetEndpoint(s string) {
	m.endpoint = &s
}

// Endpoint returns the value of the "endpoint" field in the mutation.
func (m *UpstreamProviderMutation) Endpoint() (r string, exists bool) {
	v := m.endpoint
	if v == nil {
		return
	}
	return *v, true
}

// OldEndpoint returns the old "endpoint" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldEndpoint(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEndpoint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEndpoint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEndpoint: %w", err)
	}
	return oldValue.Endpoint, nil
}

// ResetEndpoint resets all changes to the "endpoint" field.
func (m *UpstreamProviderMutation) ResetEndpoint() {
	m.endpoint = nil
}

// SetTransport sets the "transport" field.
func (m *UpstreamProviderMutation) SetTransport(u upstreamprovider.Transport) {
	m.transport = &u
}

// Transport returns the value of the "transport" field in the mutation.
func (m *UpstreamProviderMutation) Transport() (r upstreamprovider.Transport, exists bool) {
	v := m.transport
	if v == nil {
		return
	}
	return *v, true
}

// OldTransport returns the old "transport" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldTransport(ctx context.Context) (v upstreamprovider.Transport, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTransport is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTransport requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTransport: %w", err)
	}
	return oldValue.Transport, nil
}

// ResetTransport resets all changes to the "transport" field.
func (m *UpstreamProviderMutation) ResetTransport() {
	m.transport = nil
}

// SetEnabled sets the "enabled" field.
func (m *UpstreamProviderMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *UpstreamProviderMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *UpstreamProviderMutation) ResetEnabled() {
	m.enabled = nil
}

// SetLastUsedAt sets the "last_used_at" field.
func (m *UpstreamProviderMutation) SetLastUsedAt(t time.Time) {
	m.last_used_at = &t
}

// LastUsedAt returns the value of the "last_used_at" field in the mutation.
func (m *UpstreamProviderMutation) LastUsedAt() (r time.Time, exists bool) {
	v := m.last_used_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastUsedAt returns the old "last_used_at" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldLastUsedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastUsedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastUsedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastUsedAt: %w", err)
	}
	return oldValue.LastUsedAt, nil
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (m *UpstreamProviderMutation) ClearLastUsedAt() {
	m.last_used_at = nil
	m.clearedFields[upstreamprovider.FieldLastUsedAt] = struct{}{}
}

// LastUsedAtCleared returns if the "last_used_at" field was cleared in this mutation.
func (m *UpstreamProviderMutation) LastUsedAtCleared() bool {
	_, ok := m.clearedFields[upstreamprovider.FieldLastUsedAt]
	return ok
}

// ResetLastUsedAt resets all changes to the "last_used_at" field.
func (m *UpstreamProviderMutation) ResetLastUsedAt() {
	m.last_used_at = nil
	delete(m.clearedFields, upstreamprovider.FieldLastUsedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *UpstreamProviderMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UpstreamProviderMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UpstreamProviderMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UpstreamProviderMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UpstreamProviderMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the UpstreamProvider entity.
// If the UpstreamProvider object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpstreamProviderMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UpstreamProviderMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the UpstreamProviderMutation builder.
func (m *UpstreamProviderMutation) Where(ps ...predicate.UpstreamProvider) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UpstreamProviderMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UpstreamProviderMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UpstreamProvider, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UpstreamProviderMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UpstreamProviderMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UpstreamProvider).
func (m *UpstreamProviderMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UpstreamProviderMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.name != nil {
		fields = append(fields, upstreamprovider.FieldName)
	}
	if m.slug != nil {
		fields = append(fields, upstreamprovider.FieldSlug)
	}
	if m.app_id != nil {
		fields = append(fields, upstreamprovider.FieldAppID)
	}
	if m.deploy_id != nil {
		fields = append(fields, upstreamprovider.FieldDeployID)
	}
	if m.app_title != nil {
		fields = append(fields, upstreamprovider.FieldAppTitle)
	}
	if m.resource_id != nil {
		fields = append(fields, upstreamprovider.FieldResourceID)
	}
	if m.endpoint != nil {
		fields = append(fields, upstreamprovider.FieldEndpoint)
	}
	if m.transport != nil {
		fields = append(fields, upstreamprovider.FieldTransport)
	}
	if m.enabled != nil {
		fields = append(fields, upstreamprovider.FieldEnabled)
	}
	if m.last_used_at != nil {
		fields = append(fields, upstreamprovider.FieldLastUsedAt)
	}
	if m.created_at != nil {
		fields = append(fields, upstreamprovider.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, upstreamprovider.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UpstreamProviderMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case upstreamprovider.FieldName:
		return m.Name()
	case upstreamprovider.FieldSlug:
		return m.Slug()
	case upstreamprovider.FieldAppID:
		return m.AppID()
	case upstreamprovider.FieldDeployID:
		return m.DeployID()
	case upstreamprovider.FieldAppTitle:
		return m.AppTitle()
	case upstreamprovider.FieldResourceID:
		return m.ResourceID()
	case upstreamprovider.FieldEndpoint:
		return m.Endpoint()
	case upstreamprovider.FieldTransport:
		return m.Transport()
	case upstreamprovider.FieldEnabled:
		return m.Enabled()
	case upstreamprovider.FieldLastUsedAt:
		return m.LastUsedAt()
	case upstreamprovider.FieldCreatedAt:
		return m.CreatedAt()
	case upstreamprovider.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UpstreamProviderMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case upstreamprovider.FieldName:
		return m.OldName(ctx)
	case upstreamprovider.FieldSlug:
		return m.OldSlug(ctx)
	case upstreamprovider.FieldAppID:
		return m.OldAppID(ctx)
	case upstreamprovider.FieldDeployID:
		return m.OldDeployID(ctx)
	case upstreamprovider.FieldAppTitle:
		return m.OldAppTitle(ctx)
	case upstreamprovider.FieldResourceID:
		return m.OldResourceID(ctx)
	case upstreamprovider.FieldEndpoint:
		return m.OldEndpoint(ctx)
	case upstreamprovider.FieldTransport:
		return m.OldTransport(ctx)
	case upstreamprovider.FieldEnabled:
		return m.OldEnabled(ctx)
	case upstreamprovider.FieldLastUsedAt:
		return m.OldLastUsedAt(ctx)
	case upstreamprovider.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case upstreamprovider.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown UpstreamProvider field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UpstreamProviderMutation) SetField(name string, value ent.Value) error {
	switch name {
	case upstreamprovider.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case upstreamprovider.FieldSlug:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSlug(v)
		return nil
	case upstreamprovider.FieldAppID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppID(v)
		return nil
	case upstreamprovider.FieldDeployID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeployID(v)
		return nil
	case upstreamprovider.FieldAppTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAppTitle(v)
		return nil
	case upstreamprovider.FieldResourceID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResourceID(v)
		return nil
	case upstreamprovider.FieldEndpoint:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEndpoint(v)
		return nil
	case upstreamprovider.FieldTransport:
		v, ok := value.(upstreamprovider.Transport)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTransport(v)
		return nil
	case upstreamprovider.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case upstreamprovider.FieldLastUsedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastUsedAt(v)
		return nil
	case upstreamprovider.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case upstreamprovider.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown UpstreamProvider field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UpstreamProviderMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UpstreamProviderMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UpstreamProviderMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UpstreamProvider numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UpstreamProviderMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(upstreamprovider.FieldDeployID) {
		fields = append(fields, upstreamprovider.FieldDeployID)
	}
	if m.FieldCleared(upstreamprovider.FieldAppTitle) {
		fields = append(fields, upstreamprovider.FieldAppTitle)
	}
	if m.FieldCleared(upstreamprovider.FieldResourceID) {
		fields = append(fields, upstreamprovider.FieldResourceID)
	}
	if m.FieldCleared(upstreamprovider.FieldLastUsedAt) {
		fields = append(fields, upstreamprovider.FieldLastUsedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UpstreamProviderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UpstreamProviderMutation) ClearField(name string) error {
	switch name {
	case upstreamprovider.FieldDeployID:
		m.ClearDeployID()
		return nil
	case upstreamprovider.FieldAppTitle:
		m.ClearAppTitle()
		return nil
	case upstreamprovider.FieldResourceID:
		m.ClearResourceID()
		return nil
	case upstreamprovider.FieldLastUsedAt:
		m.ClearLastUsedAt()
		return nil
	}
	return fmt.Errorf("unknown UpstreamProvider nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UpstreamProviderMutation) ResetField(name string) error {
	switch name {
	case upstreamprovider.FieldName:
		m.ResetName()
		return nil
	case upstreamprovider.FieldSlug:
		m.ResetSlug()
		return nil
	case upstreamprovider.FieldAppID:
		m.ResetAppID()
		return nil
	case upstreamprovider.FieldDeployID:
		m.ResetDeployID()
		return nil
	case upstreamprovider.FieldAppTitle:
		m.ResetAppTitle()
		return nil
	case upstreamprovider.FieldResourceID:
		m.ResetResourceID()
		return nil
	case upstreamprovider.FieldEndpoint:
		m.ResetEndpoint()
		return nil
	case upstreamprovider.FieldTransport:
		m.ResetTransport()
		return nil
	case upstreamprovider.FieldEnabled:
		m.ResetEnabled()
		return nil
	case upstreamprovider.FieldLastUsedAt:
		m.ResetLastUsedAt()
		return nil
	case upstreamprovider.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case upstreamprovider.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown UpstreamProvider field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UpstreamProviderMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UpstreamProviderMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UpstreamProviderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UpstreamProviderMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UpstreamProviderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UpstreamProviderMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UpstreamProviderMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UpstreamProvider unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UpstreamProviderMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UpstreamProvider edge %s", name)
}
