// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lazycat-mcp/ent/mcptoken"
	"lazycat-mcp/ent/schema"
	"lazycat-mcp/ent/upstreamprovider"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mcptokenFields := schema.MCPToken{}.Fields()
	_ = mcptokenFields
	// mcptokenDescName is the schema descriptor for name field.
	mcptokenDescName := mcptokenFields[0].Descriptor()
	// mcptoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mcptoken.NameValidator = func() func(string) error {
		validators := mcptokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mcptokenDescTokenHash is the schema descriptor for token_hash field.
	mcptokenDescTokenHash := mcptokenFields[1].Descriptor()
	// mcptoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	mcptoken.TokenHashValidator = mcptokenDescTokenHash.Validators[0].(func(string) error)
	// mcptokenDescPrefix is the schema descriptor for prefix field.
	mcptokenDescPrefix := mcptokenFields[2].Descriptor()
	// mcptoken.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	mcptoken.PrefixValidator = func() func(string) error {
		validators := mcptokenDescPrefix.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(prefix string) error {
			for _, fn := range fns {
				if err := fn(prefix); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mcptokenDescEnabled is the schema descriptor for enabled field.
	mcptokenDescEnabled := mcptokenFields[3].Descriptor()
	// mcptoken.DefaultEnabled holds the default value on creation for the enabled field.
	mcptoken.DefaultEnabled = mcptokenDescEnabled.Default.(bool)
	// mcptokenDescCreatedAt is the schema descriptor for created_at field.
	mcptokenDescCreatedAt := mcptokenFields[6].Descriptor()
	// mcptoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcptoken.DefaultCreatedAt = mcptokenDescCreatedAt.Default.(func() time.Time)
	// mcptokenDescUpdatedAt is the schema descriptor for updated_at field.
	mcptokenDescUpdatedAt := mcptokenFields[7].Descriptor()
	// mcptoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mcptoken.DefaultUpdatedAt = mcptokenDescUpdatedAt.Default.(func() time.Time)
	// mcptoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mcptoken.UpdateDefaultUpdatedAt = mcptokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	upstreamproviderFields := schema.UpstreamProvider{}.Fields()
	_ = upstreamproviderFields
	// upstreamproviderDescName is the schema descriptor for name field.
	upstreamproviderDescName := upstreamproviderFields[0].Descriptor()
	// upstreamprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	upstreamprovider.NameValidator = func() func(string) error {
		validators := upstreamproviderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// upstreamproviderDescDescription is the schema descriptor for description field.
	upstreamproviderDescDescription := upstreamproviderFields[1].Descriptor()
	// upstreamprovider.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	upstreamprovider.DescriptionValidator = upstreamproviderDescDescription.Validators[0].(func(string) error)
	// upstreamproviderDescSlug is the schema descriptor for slug field.
	upstreamproviderDescSlug := upstreamproviderFields[2].Descriptor()
	// upstreamprovider.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	upstreamprovider.SlugValidator = func() func(string) error {
		validators := upstreamproviderDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// upstreamproviderDescAppID is the schema descriptor for app_id field.
	upstreamproviderDescAppID := upstreamproviderFields[4].Descriptor()
	// upstreamprovider.DefaultAppID holds the default value on creation for the app_id field.
	upstreamprovider.DefaultAppID = upstreamproviderDescAppID.Default.(string)
	// upstreamprovider.AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	upstreamprovider.AppIDValidator = upstreamproviderDescAppID.Validators[0].(func(string) error)
	// upstreamproviderDescDeployID is the schema descriptor for deploy_id field.
	upstreamproviderDescDeployID := upstreamproviderFields[5].Descriptor()
	// upstreamprovider.DeployIDValidator is a validator for the "deploy_id" field. It is called by the builders before save.
	upstreamprovider.DeployIDValidator = upstreamproviderDescDeployID.Validators[0].(func(string) error)
	// upstreamproviderDescAppTitle is the schema descriptor for app_title field.
	upstreamproviderDescAppTitle := upstreamproviderFields[6].Descriptor()
	// upstreamprovider.AppTitleValidator is a validator for the "app_title" field. It is called by the builders before save.
	upstreamprovider.AppTitleValidator = upstreamproviderDescAppTitle.Validators[0].(func(string) error)
	// upstreamproviderDescResourceID is the schema descriptor for resource_id field.
	upstreamproviderDescResourceID := upstreamproviderFields[7].Descriptor()
	// upstreamprovider.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	upstreamprovider.ResourceIDValidator = upstreamproviderDescResourceID.Validators[0].(func(string) error)
	// upstreamproviderDescBaseURL is the schema descriptor for base_url field.
	upstreamproviderDescBaseURL := upstreamproviderFields[8].Descriptor()
	// upstreamprovider.BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	upstreamprovider.BaseURLValidator = upstreamproviderDescBaseURL.Validators[0].(func(string) error)
	// upstreamproviderDescEndpoint is the schema descriptor for endpoint field.
	upstreamproviderDescEndpoint := upstreamproviderFields[9].Descriptor()
	// upstreamprovider.DefaultEndpoint holds the default value on creation for the endpoint field.
	upstreamprovider.DefaultEndpoint = upstreamproviderDescEndpoint.Default.(string)
	// upstreamprovider.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	upstreamprovider.EndpointValidator = func() func(string) error {
		validators := upstreamproviderDescEndpoint.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(endpoint string) error {
			for _, fn := range fns {
				if err := fn(endpoint); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// upstreamproviderDescHeaders is the schema descriptor for headers field.
	upstreamproviderDescHeaders := upstreamproviderFields[10].Descriptor()
	// upstreamprovider.DefaultHeaders holds the default value on creation for the headers field.
	upstreamprovider.DefaultHeaders = upstreamproviderDescHeaders.Default.(string)
	// upstreamproviderDescEnabled is the schema descriptor for enabled field.
	upstreamproviderDescEnabled := upstreamproviderFields[12].Descriptor()
	// upstreamprovider.DefaultEnabled holds the default value on creation for the enabled field.
	upstreamprovider.DefaultEnabled = upstreamproviderDescEnabled.Default.(bool)
	// upstreamproviderDescCreatedAt is the schema descriptor for created_at field.
	upstreamproviderDescCreatedAt := upstreamproviderFields[14].Descriptor()
	// upstreamprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	upstreamprovider.DefaultCreatedAt = upstreamproviderDescCreatedAt.Default.(func() time.Time)
	// upstreamproviderDescUpdatedAt is the schema descriptor for updated_at field.
	upstreamproviderDescUpdatedAt := upstreamproviderFields[15].Descriptor()
	// upstreamprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	upstreamprovider.DefaultUpdatedAt = upstreamproviderDescUpdatedAt.Default.(func() time.Time)
	// upstreamprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	upstreamprovider.UpdateDefaultUpdatedAt = upstreamproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
}
