// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lazycat-mcp/ent/predicate"
	"lazycat-mcp/ent/upstreamprovider"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpstreamProviderUpdate is the builder for updating UpstreamProvider entities.
type UpstreamProviderUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamProviderMutation
}

// Where appends a list predicates to the UpstreamProviderUpdate builder.
func (_u *UpstreamProviderUpdate) Where(ps ...predicate.UpstreamProvider) *UpstreamProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamProviderUpdate) SetName(v string) *UpstreamProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableName(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpstreamProviderUpdate) SetDescription(v string) *UpstreamProviderUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableDescription(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UpstreamProviderUpdate) ClearDescription() *UpstreamProviderUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *UpstreamProviderUpdate) SetSlug(v string) *UpstreamProviderUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableSlug(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *UpstreamProviderUpdate) SetProviderType(v upstreamprovider.ProviderType) *UpstreamProviderUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableProviderType(v *upstreamprovider.ProviderType) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *UpstreamProviderUpdate) SetAppID(v string) *UpstreamProviderUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableAppID(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *UpstreamProviderUpdate) SetOwnerUserID(v string) *UpstreamProviderUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableOwnerUserID(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetDeployID sets the "deploy_id" field.
func (_u *UpstreamProviderUpdate) SetDeployID(v string) *UpstreamProviderUpdate {
	_u.mutation.SetDeployID(v)
	return _u
}

// SetNillableDeployID sets the "deploy_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableDeployID(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetDeployID(*v)
	}
	return _u
}

// ClearDeployID clears the value of the "deploy_id" field.
func (_u *UpstreamProviderUpdate) ClearDeployID() *UpstreamProviderUpdate {
	_u.mutation.ClearDeployID()
	return _u
}

// SetAppTitle sets the "app_title" field.
func (_u *UpstreamProviderUpdate) SetAppTitle(v string) *UpstreamProviderUpdate {
	_u.mutation.SetAppTitle(v)
	return _u
}

// SetNillableAppTitle sets the "app_title" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableAppTitle(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetAppTitle(*v)
	}
	return _u
}

// ClearAppTitle clears the value of the "app_title" field.
func (_u *UpstreamProviderUpdate) ClearAppTitle() *UpstreamProviderUpdate {
	_u.mutation.ClearAppTitle()
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UpstreamProviderUpdate) SetResourceID(v string) *UpstreamProviderUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableResourceID(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *UpstreamProviderUpdate) ClearResourceID() *UpstreamProviderUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamProviderUpdate) SetBaseURL(v string) *UpstreamProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableBaseURL(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *UpstreamProviderUpdate) ClearBaseURL() *UpstreamProviderUpdate {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *UpstreamProviderUpdate) SetEndpoint(v string) *UpstreamProviderUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableEndpoint(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *UpstreamProviderUpdate) SetHeaders(v string) *UpstreamProviderUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetNillableHeaders sets the "headers" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableHeaders(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetHeaders(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *UpstreamProviderUpdate) SetTransport(v upstreamprovider.Transport) *UpstreamProviderUpdate {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableTransport(v *upstreamprovider.Transport) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamProviderUpdate) SetEnabled(v bool) *UpstreamProviderUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableEnabled(v *bool) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UpstreamProviderUpdate) SetLastUsedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableLastUsedAt(v *time.Time) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UpstreamProviderUpdate) ClearLastUsedAt() *UpstreamProviderUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamProviderUpdate) SetUpdatedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_u *UpstreamProviderUpdate) Mutation() *UpstreamProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := upstreamprovider.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := upstreamprovider.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := upstreamprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := upstreamprovider.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := upstreamprovider.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeployID(); ok {
		if err := upstreamprovider.DeployIDValidator(v); err != nil {
			return &ValidationError{Name: "deploy_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.deploy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppTitle(); ok {
		if err := upstreamprovider.AppTitleValidator(v); err != nil {
			return &ValidationError{Name: "app_title", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.app_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := upstreamprovider.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := upstreamprovider.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := upstreamprovider.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.transport": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamprovider.Table, upstreamprovider.Columns, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upstreamprovider.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(upstreamprovider.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(upstreamprovider.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(upstreamprovider.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(upstreamprovider.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(upstreamprovider.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeployID(); ok {
		_spec.SetField(upstreamprovider.FieldDeployID, field.TypeString, value)
	}
	if _u.mutation.DeployIDCleared() {
		_spec.ClearField(upstreamprovider.FieldDeployID, field.TypeString)
	}
	if value, ok := _u.mutation.AppTitle(); ok {
		_spec.SetField(upstreamprovider.FieldAppTitle, field.TypeString, value)
	}
	if _u.mutation.AppTitleCleared() {
		_spec.ClearField(upstreamprovider.FieldAppTitle, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(upstreamprovider.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(upstreamprovider.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(upstreamprovider.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(upstreamprovider.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(upstreamprovider.FieldHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(upstreamprovider.FieldTransport, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamprovider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamProviderUpdateOne is the builder for updating a single UpstreamProvider entity.
type UpstreamProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamProviderMutation
}

// SetName sets the "name" field.
func (_u *UpstreamProviderUpdateOne) SetName(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableName(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UpstreamProviderUpdateOne) SetDescription(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableDescription(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UpstreamProviderUpdateOne) ClearDescription() *UpstreamProviderUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSlug sets the "slug" field.
func (_u *UpstreamProviderUpdateOne) SetSlug(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableSlug(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *UpstreamProviderUpdateOne) SetProviderType(v upstreamprovider.ProviderType) *UpstreamProviderUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableProviderType(v *upstreamprovider.ProviderType) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *UpstreamProviderUpdateOne) SetAppID(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableAppID(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *UpstreamProviderUpdateOne) SetOwnerUserID(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableOwnerUserID(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetDeployID sets the "deploy_id" field.
func (_u *UpstreamProviderUpdateOne) SetDeployID(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetDeployID(v)
	return _u
}

// SetNillableDeployID sets the "deploy_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableDeployID(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetDeployID(*v)
	}
	return _u
}

// ClearDeployID clears the value of the "deploy_id" field.
func (_u *UpstreamProviderUpdateOne) ClearDeployID() *UpstreamProviderUpdateOne {
	_u.mutation.ClearDeployID()
	return _u
}

// SetAppTitle sets the "app_title" field.
func (_u *UpstreamProviderUpdateOne) SetAppTitle(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetAppTitle(v)
	return _u
}

// SetNillableAppTitle sets the "app_title" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableAppTitle(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetAppTitle(*v)
	}
	return _u
}

// ClearAppTitle clears the value of the "app_title" field.
func (_u *UpstreamProviderUpdateOne) ClearAppTitle() *UpstreamProviderUpdateOne {
	_u.mutation.ClearAppTitle()
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UpstreamProviderUpdateOne) SetResourceID(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableResourceID(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *UpstreamProviderUpdateOne) ClearResourceID() *UpstreamProviderUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamProviderUpdateOne) SetBaseURL(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableBaseURL(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *UpstreamProviderUpdateOne) ClearBaseURL() *UpstreamProviderUpdateOne {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *UpstreamProviderUpdateOne) SetEndpoint(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableEndpoint(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *UpstreamProviderUpdateOne) SetHeaders(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// SetNillableHeaders sets the "headers" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableHeaders(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetHeaders(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *UpstreamProviderUpdateOne) SetTransport(v upstreamprovider.Transport) *UpstreamProviderUpdateOne {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableTransport(v *upstreamprovider.Transport) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamProviderUpdateOne) SetEnabled(v bool) *UpstreamProviderUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableEnabled(v *bool) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UpstreamProviderUpdateOne) SetLastUsedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableLastUsedAt(v *time.Time) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UpstreamProviderUpdateOne) ClearLastUsedAt() *UpstreamProviderUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamProviderUpdateOne) SetUpdatedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_u *UpstreamProviderUpdateOne) Mutation() *UpstreamProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamProviderUpdate builder.
func (_u *UpstreamProviderUpdateOne) Where(ps ...predicate.UpstreamProvider) *UpstreamProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamProviderUpdateOne) Select(field string, fields ...string) *UpstreamProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamProvider entity.
func (_u *UpstreamProviderUpdateOne) Save(ctx context.Context) (*UpstreamProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamProviderUpdateOne) SaveX(ctx context.Context) *UpstreamProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := upstreamprovider.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := upstreamprovider.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := upstreamprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := upstreamprovider.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := upstreamprovider.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeployID(); ok {
		if err := upstreamprovider.DeployIDValidator(v); err != nil {
			return &ValidationError{Name: "deploy_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.deploy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppTitle(); ok {
		if err := upstreamprovider.AppTitleValidator(v); err != nil {
			return &ValidationError{Name: "app_title", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.app_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := upstreamprovider.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := upstreamprovider.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := upstreamprovider.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.transport": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamProviderUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamprovider.Table, upstreamprovider.Columns, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamprovider.FieldID)
		for _, f := range fields {
			if !upstreamprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(upstreamprovider.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(upstreamprovider.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(upstreamprovider.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(upstreamprovider.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(upstreamprovider.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(upstreamprovider.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeployID(); ok {
		_spec.SetField(upstreamprovider.FieldDeployID, field.TypeString, value)
	}
	if _u.mutation.DeployIDCleared() {
		_spec.ClearField(upstreamprovider.FieldDeployID, field.TypeString)
	}
	if value, ok := _u.mutation.AppTitle(); ok {
		_spec.SetField(upstreamprovider.FieldAppTitle, field.TypeString, value)
	}
	if _u.mutation.AppTitleCleared() {
		_spec.ClearField(upstreamprovider.FieldAppTitle, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(upstreamprovider.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(upstreamprovider.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(upstreamprovider.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(upstreamprovider.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(upstreamprovider.FieldHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(upstreamprovider.FieldTransport, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamprovider.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UpstreamProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
