// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"lazycat-mcp/ent/upstreamprovider"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UpstreamProvider is the model entity for the UpstreamProvider schema.
type UpstreamProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType upstreamprovider.ProviderType `json:"provider_type,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID string `json:"app_id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID string `json:"owner_user_id,omitempty"`
	// DeployID holds the value of the "deploy_id" field.
	DeployID *string `json:"deploy_id,omitempty"`
	// AppTitle holds the value of the "app_title" field.
	AppTitle *string `json:"app_title,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID *string `json:"resource_id,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL *string `json:"base_url,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers string `json:"-"`
	// Transport holds the value of the "transport" field.
	Transport upstreamprovider.Transport `json:"transport,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamprovider.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreamprovider.FieldID:
			values[i] = new(sql.NullInt64)
		case upstreamprovider.FieldName, upstreamprovider.FieldDescription, upstreamprovider.FieldSlug, upstreamprovider.FieldProviderType, upstreamprovider.FieldAppID, upstreamprovider.FieldOwnerUserID, upstreamprovider.FieldDeployID, upstreamprovider.FieldAppTitle, upstreamprovider.FieldResourceID, upstreamprovider.FieldBaseURL, upstreamprovider.FieldEndpoint, upstreamprovider.FieldHeaders, upstreamprovider.FieldTransport:
			values[i] = new(sql.NullString)
		case upstreamprovider.FieldLastUsedAt, upstreamprovider.FieldCreatedAt, upstreamprovider.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamProvider fields.
func (_m *UpstreamProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case upstreamprovider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamprovider.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case upstreamprovider.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case upstreamprovider.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = upstreamprovider.ProviderType(value.String)
			}
		case upstreamprovider.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case upstreamprovider.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.String
			}
		case upstreamprovider.FieldDeployID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deploy_id", values[i])
			} else if value.Valid {
				_m.DeployID = new(string)
				*_m.DeployID = value.String
			}
		case upstreamprovider.FieldAppTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_title", values[i])
			} else if value.Valid {
				_m.AppTitle = new(string)
				*_m.AppTitle = value.String
			}
		case upstreamprovider.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = new(string)
				*_m.ResourceID = value.String
			}
		case upstreamprovider.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = new(string)
				*_m.BaseURL = value.String
			}
		case upstreamprovider.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case upstreamprovider.FieldHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value.Valid {
				_m.Headers = value.String
			}
		case upstreamprovider.FieldTransport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transport", values[i])
			} else if value.Valid {
				_m.Transport = upstreamprovider.Transport(value.String)
			}
		case upstreamprovider.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstreamprovider.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case upstreamprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamprovider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamProvider.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamProvider.
// Note that you need to call UpstreamProvider.Unwrap() before calling this method if this UpstreamProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamProvider) Update() *UpstreamProviderUpdateOne {
	return NewUpstreamProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamProvider) Unwrap() *UpstreamProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamProvider) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderType))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(_m.OwnerUserID)
	builder.WriteString(", ")
	if v := _m.DeployID; v != nil {
		builder.WriteString("deploy_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AppTitle; v != nil {
		builder.WriteString("app_title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResourceID; v != nil {
		builder.WriteString("resource_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BaseURL; v != nil {
		builder.WriteString("base_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("headers=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("transport=")
	builder.WriteString(fmt.Sprintf("%v", _m.Transport))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamProviders is a parsable slice of UpstreamProvider.
type UpstreamProviders []*UpstreamProvider
