// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lazycat-mcp/ent/upstreamprovider"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpstreamProviderCreate is the builder for creating a UpstreamProvider entity.
type UpstreamProviderCreate struct {
	config
	mutation *UpstreamProviderMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *UpstreamProviderCreate) SetName(v string) *UpstreamProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *UpstreamProviderCreate) SetDescription(v string) *UpstreamProviderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableDescription(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *UpstreamProviderCreate) SetSlug(v string) *UpstreamProviderCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetProviderType sets the "provider_type" field.
func (_c *UpstreamProviderCreate) SetProviderType(v upstreamprovider.ProviderType) *UpstreamProviderCreate {
	_c.mutation.SetProviderType(v)
	return _c
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableProviderType(v *upstreamprovider.ProviderType) *UpstreamProviderCreate {
	if v != nil {
		_c.SetProviderType(*v)
	}
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *UpstreamProviderCreate) SetAppID(v string) *UpstreamProviderCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableAppID(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetAppID(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *UpstreamProviderCreate) SetOwnerUserID(v string) *UpstreamProviderCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableOwnerUserID(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetOwnerUserID(*v)
	}
	return _c
}

// SetDeployID sets the "deploy_id" field.
func (_c *UpstreamProviderCreate) SetDeployID(v string) *UpstreamProviderCreate {
	_c.mutation.SetDeployID(v)
	return _c
}

// SetNillableDeployID sets the "deploy_id" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableDeployID(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetDeployID(*v)
	}
	return _c
}

// SetAppTitle sets the "app_title" field.
func (_c *UpstreamProviderCreate) SetAppTitle(v string) *UpstreamProviderCreate {
	_c.mutation.SetAppTitle(v)
	return _c
}

// SetNillableAppTitle sets the "app_title" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableAppTitle(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetAppTitle(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *UpstreamProviderCreate) SetResourceID(v string) *UpstreamProviderCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableResourceID(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamProviderCreate) SetBaseURL(v string) *UpstreamProviderCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableBaseURL(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetBaseURL(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *UpstreamProviderCreate) SetEndpoint(v string) *UpstreamProviderCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableEndpoint(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *UpstreamProviderCreate) SetHeaders(v string) *UpstreamProviderCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetNillableHeaders sets the "headers" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableHeaders(v *string) *UpstreamProviderCreate {
	if v != nil {
		_c.SetHeaders(*v)
	}
	return _c
}

// SetTransport sets the "transport" field.
func (_c *UpstreamProviderCreate) SetTransport(v upstreamprovider.Transport) *UpstreamProviderCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableTransport(v *upstreamprovider.Transport) *UpstreamProviderCreate {
	if v != nil {
		_c.SetTransport(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamProviderCreate) SetEnabled(v bool) *UpstreamProviderCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableEnabled(v *bool) *UpstreamProviderCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *UpstreamProviderCreate) SetLastUsedAt(v time.Time) *UpstreamProviderCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableLastUsedAt(v *time.Time) *UpstreamProviderCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamProviderCreate) SetCreatedAt(v time.Time) *UpstreamProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableCreatedAt(v *time.Time) *UpstreamProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamProviderCreate) SetUpdatedAt(v time.Time) *UpstreamProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamProviderCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_c *UpstreamProviderCreate) Mutation() *UpstreamProviderMutation {
	return _c.mutation
}

// Save creates the UpstreamProvider in the database.
func (_c *UpstreamProviderCreate) Save(ctx context.Context) (*UpstreamProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamProviderCreate) SaveX(ctx context.Context) *UpstreamProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamProviderCreate) defaults() {
	if _, ok := _c.mutation.ProviderType(); !ok {
		v := upstreamprovider.DefaultProviderType
		_c.mutation.SetProviderType(v)
	}
	if _, ok := _c.mutation.AppID(); !ok {
		v := upstreamprovider.DefaultAppID
		_c.mutation.SetAppID(v)
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		v := upstreamprovider.DefaultOwnerUserID
		_c.mutation.SetOwnerUserID(v)
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		v := upstreamprovider.DefaultEndpoint
		_c.mutation.SetEndpoint(v)
	}
	if _, ok := _c.mutation.Headers(); !ok {
		v := upstreamprovider.DefaultHeaders
		_c.mutation.SetHeaders(v)
	}
	if _, ok := _c.mutation.Transport(); !ok {
		v := upstreamprovider.DefaultTransport
		_c.mutation.SetTransport(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstreamprovider.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamProviderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := upstreamprovider.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "UpstreamProvider.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := upstreamprovider.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		return &ValidationError{Name: "provider_type", err: errors.New(`ent: missing required field "UpstreamProvider.provider_type"`)}
	}
	if v, ok := _c.mutation.ProviderType(); ok {
		if err := upstreamprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.provider_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "UpstreamProvider.app_id"`)}
	}
	if v, ok := _c.mutation.AppID(); ok {
		if err := upstreamprovider.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "UpstreamProvider.owner_user_id"`)}
	}
	if v, ok := _c.mutation.OwnerUserID(); ok {
		if err := upstreamprovider.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeployID(); ok {
		if err := upstreamprovider.DeployIDValidator(v); err != nil {
			return &ValidationError{Name: "deploy_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.deploy_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AppTitle(); ok {
		if err := upstreamprovider.AppTitleValidator(v); err != nil {
			return &ValidationError{Name: "app_title", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.app_title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := upstreamprovider.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.resource_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstreamprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "UpstreamProvider.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := upstreamprovider.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Headers(); !ok {
		return &ValidationError{Name: "headers", err: errors.New(`ent: missing required field "UpstreamProvider.headers"`)}
	}
	if _, ok := _c.mutation.Transport(); !ok {
		return &ValidationError{Name: "transport", err: errors.New(`ent: missing required field "UpstreamProvider.transport"`)}
	}
	if v, ok := _c.mutation.Transport(); ok {
		if err := upstreamprovider.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.transport": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UpstreamProvider.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamProvider.updated_at"`)}
	}
	return nil
}

func (_c *UpstreamProviderCreate) sqlSave(ctx context.Context) (*UpstreamProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamProviderCreate) createSpec() (*UpstreamProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamprovider.Table, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(upstreamprovider.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(upstreamprovider.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.ProviderType(); ok {
		_spec.SetField(upstreamprovider.FieldProviderType, field.TypeEnum, value)
		_node.ProviderType = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(upstreamprovider.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(upstreamprovider.FieldOwnerUserID, field.TypeString, value)
		_node.OwnerUserID = value
	}
	if value, ok := _c.mutation.DeployID(); ok {
		_spec.SetField(upstreamprovider.FieldDeployID, field.TypeString, value)
		_node.DeployID = &value
	}
	if value, ok := _c.mutation.AppTitle(); ok {
		_spec.SetField(upstreamprovider.FieldAppTitle, field.TypeString, value)
		_node.AppTitle = &value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(upstreamprovider.FieldResourceID, field.TypeString, value)
		_node.ResourceID = &value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = &value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(upstreamprovider.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(upstreamprovider.FieldHeaders, field.TypeString, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(upstreamprovider.FieldTransport, field.TypeEnum, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstreamprovider.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UpstreamProviderCreateBulk is the builder for creating many UpstreamProvider entities in bulk.
type UpstreamProviderCreateBulk struct {
	config
	err      error
	builders []*UpstreamProviderCreate
}

// Save creates the UpstreamProvider entities in the database.
func (_c *UpstreamProviderCreateBulk) Save(ctx context.Context) ([]*UpstreamProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamProviderCreateBulk) SaveX(ctx context.Context) []*UpstreamProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
