// Code generated by ent, DO NOT EDIT.

package upstreamprovider

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamprovider type in the database.
	Label = "upstream_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "type"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldDeployID holds the string denoting the deploy_id field in the database.
	FieldDeployID = "deploy_id"
	// FieldAppTitle holds the string denoting the app_title field in the database.
	FieldAppTitle = "app_title"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldTransport holds the string denoting the transport field in the database.
	FieldTransport = "transport"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the upstreamprovider in the database.
	Table = "upstream_providers"
)

// Columns holds all SQL columns for upstreamprovider fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldSlug,
	FieldProviderType,
	FieldAppID,
	FieldOwnerUserID,
	FieldDeployID,
	FieldAppTitle,
	FieldResourceID,
	FieldBaseURL,
	FieldEndpoint,
	FieldHeaders,
	FieldTransport,
	FieldEnabled,
	FieldLastUsedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultAppID holds the default value on creation for the "app_id" field.
	DefaultAppID string
	// AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	AppIDValidator func(string) error
	// DefaultOwnerUserID holds the default value on creation for the "owner_user_id" field.
	DefaultOwnerUserID string
	// OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	OwnerUserIDValidator func(string) error
	// DeployIDValidator is a validator for the "deploy_id" field. It is called by the builders before save.
	DeployIDValidator func(string) error
	// AppTitleValidator is a validator for the "app_title" field. It is called by the builders before save.
	AppTitleValidator func(string) error
	// ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	ResourceIDValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultHeaders holds the default value on creation for the "headers" field.
	DefaultHeaders string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ProviderType defines the type for the "provider_type" enum field.
type ProviderType string

// ProviderTypeLazycat is the default value of the ProviderType enum.
const DefaultProviderType = ProviderTypeLazycat

// ProviderType values.
const (
	ProviderTypeLazycat ProviderType = "lazycat"
	ProviderTypeCustom  ProviderType = "custom"
)

func (pt ProviderType) String() string {
	return string(pt)
}

// ProviderTypeValidator is a validator for the "provider_type" field enum values. It is called by the builders before save.
func ProviderTypeValidator(pt ProviderType) error {
	switch pt {
	case ProviderTypeLazycat, ProviderTypeCustom:
		return nil
	default:
		return fmt.Errorf("upstreamprovider: invalid enum value for provider_type field: %q", pt)
	}
}

// Transport defines the type for the "transport" enum field.
type Transport string

// TransportStreamableHTTP is the default value of the Transport enum.
const DefaultTransport = TransportStreamableHTTP

// Transport values.
const (
	TransportStreamableHTTP Transport = "streamable_http"
	TransportSse            Transport = "sse"
)

func (t Transport) String() string {
	return string(t)
}

// TransportValidator is a validator for the "transport" field enum values. It is called by the builders before save.
func TransportValidator(t Transport) error {
	switch t {
	case TransportStreamableHTTP, TransportSse:
		return nil
	default:
		return fmt.Errorf("upstreamprovider: invalid enum value for transport field: %q", t)
	}
}

// OrderOption defines the ordering options for the UpstreamProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByProviderType orders the results by the provider_type field.
func ByProviderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderType, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByDeployID orders the results by the deploy_id field.
func ByDeployID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeployID, opts...).ToFunc()
}

// ByAppTitle orders the results by the app_title field.
func ByAppTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppTitle, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByHeaders orders the results by the headers field.
func ByHeaders(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaders, opts...).ToFunc()
}

// ByTransport orders the results by the transport field.
func ByTransport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransport, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
