// Code generated by ent, DO NOT EDIT.

package upstreamprovider

import (
	"lazycat-mcp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldSlug, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldAppID, v))
}

// DeployID applies equality check predicate on the "deploy_id" field. It's identical to DeployIDEQ.
func DeployID(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldDeployID, v))
}

// AppTitle applies equality check predicate on the "app_title" field. It's identical to AppTitleEQ.
func AppTitle(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldAppTitle, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldResourceID, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldEndpoint, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldEnabled, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldSlug, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldAppID, v))
}

// DeployIDEQ applies the EQ predicate on the "deploy_id" field.
func DeployIDEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldDeployID, v))
}

// DeployIDNEQ applies the NEQ predicate on the "deploy_id" field.
func DeployIDNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldDeployID, v))
}

// DeployIDIn applies the In predicate on the "deploy_id" field.
func DeployIDIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldDeployID, vs...))
}

// DeployIDNotIn applies the NotIn predicate on the "deploy_id" field.
func DeployIDNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldDeployID, vs...))
}

// DeployIDGT applies the GT predicate on the "deploy_id" field.
func DeployIDGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldDeployID, v))
}

// DeployIDGTE applies the GTE predicate on the "deploy_id" field.
func DeployIDGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldDeployID, v))
}

// DeployIDLT applies the LT predicate on the "deploy_id" field.
func DeployIDLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldDeployID, v))
}

// DeployIDLTE applies the LTE predicate on the "deploy_id" field.
func DeployIDLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldDeployID, v))
}

// DeployIDContains applies the Contains predicate on the "deploy_id" field.
func DeployIDContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldDeployID, v))
}

// DeployIDHasPrefix applies the HasPrefix predicate on the "deploy_id" field.
func DeployIDHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldDeployID, v))
}

// DeployIDHasSuffix applies the HasSuffix predicate on the "deploy_id" field.
func DeployIDHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldDeployID, v))
}

// DeployIDIsNil applies the IsNil predicate on the "deploy_id" field.
func DeployIDIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldDeployID))
}

// DeployIDNotNil applies the NotNil predicate on the "deploy_id" field.
func DeployIDNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldDeployID))
}

// DeployIDEqualFold applies the EqualFold predicate on the "deploy_id" field.
func DeployIDEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldDeployID, v))
}

// DeployIDContainsFold applies the ContainsFold predicate on the "deploy_id" field.
func DeployIDContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldDeployID, v))
}

// AppTitleEQ applies the EQ predicate on the "app_title" field.
func AppTitleEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldAppTitle, v))
}

// AppTitleNEQ applies the NEQ predicate on the "app_title" field.
func AppTitleNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldAppTitle, v))
}

// AppTitleIn applies the In predicate on the "app_title" field.
func AppTitleIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldAppTitle, vs...))
}

// AppTitleNotIn applies the NotIn predicate on the "app_title" field.
func AppTitleNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldAppTitle, vs...))
}

// AppTitleGT applies the GT predicate on the "app_title" field.
func AppTitleGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldAppTitle, v))
}

// AppTitleGTE applies the GTE predicate on the "app_title" field.
func AppTitleGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldAppTitle, v))
}

// AppTitleLT applies the LT predicate on the "app_title" field.
func AppTitleLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldAppTitle, v))
}

// AppTitleLTE applies the LTE predicate on the "app_title" field.
func AppTitleLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldAppTitle, v))
}

// AppTitleContains applies the Contains predicate on the "app_title" field.
func AppTitleContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldAppTitle, v))
}

// AppTitleHasPrefix applies the HasPrefix predicate on the "app_title" field.
func AppTitleHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldAppTitle, v))
}

// AppTitleHasSuffix applies the HasSuffix predicate on the "app_title" field.
func AppTitleHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldAppTitle, v))
}

// AppTitleIsNil applies the IsNil predicate on the "app_title" field.
func AppTitleIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldAppTitle))
}

// AppTitleNotNil applies the NotNil predicate on the "app_title" field.
func AppTitleNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldAppTitle))
}

// AppTitleEqualFold applies the EqualFold predicate on the "app_title" field.
func AppTitleEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldAppTitle, v))
}

// AppTitleContainsFold applies the ContainsFold predicate on the "app_title" field.
func AppTitleContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldAppTitle, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDIsNil applies the IsNil predicate on the "resource_id" field.
func ResourceIDIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldResourceID))
}

// ResourceIDNotNil applies the NotNil predicate on the "resource_id" field.
func ResourceIDNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldResourceID))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldResourceID, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldEndpoint, v))
}

// TransportEQ applies the EQ predicate on the "transport" field.
func TransportEQ(v Transport) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTransport, v))
}

// TransportNEQ applies the NEQ predicate on the "transport" field.
func TransportNEQ(v Transport) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldTransport, v))
}

// TransportIn applies the In predicate on the "transport" field.
func TransportIn(vs ...Transport) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldTransport, vs...))
}

// TransportNotIn applies the NotIn predicate on the "transport" field.
func TransportNotIn(vs ...Transport) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldTransport, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldEnabled, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.NotPredicates(p))
}
