// Code generated by ent, DO NOT EDIT.

package mcpcalllog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mcpcalllog type in the database.
	Label = "mcp_call_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldTransport holds the string denoting the transport field in the database.
	FieldTransport = "transport"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldProviderSlug holds the string denoting the provider_slug field in the database.
	FieldProviderSlug = "provider_slug"
	// FieldTokenPrefix holds the string denoting the token_prefix field in the database.
	FieldTokenPrefix = "token_prefix"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the mcpcalllog in the database.
	Table = "mcp_call_logs"
)

// Columns holds all SQL columns for mcpcalllog fields.
var Columns = []string{
	FieldID,
	FieldSource,
	FieldTransport,
	FieldMethod,
	FieldTarget,
	FieldProviderSlug,
	FieldTokenPrefix,
	FieldSessionID,
	FieldRequestID,
	FieldStatus,
	FieldStatusCode,
	FieldDurationMs,
	FieldError,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// TargetValidator is a validator for the "target" field. It is called by the builders before save.
	TargetValidator func(string) error
	// ProviderSlugValidator is a validator for the "provider_slug" field. It is called by the builders before save.
	ProviderSlugValidator func(string) error
	// TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	TokenPrefixValidator func(string) error
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// StatusCodeValidator is a validator for the "status_code" field. It is called by the builders before save.
	StatusCodeValidator func(int) error
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int64
	// DurationMsValidator is a validator for the "duration_ms" field. It is called by the builders before save.
	DurationMsValidator func(int64) error
	// ErrorValidator is a validator for the "error" field. It is called by the builders before save.
	ErrorValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Source defines the type for the "source" enum field.
type Source string

// SourceLocal is the default value of the Source enum.
const DefaultSource = SourceLocal

// Source values.
const (
	SourceLocal    Source = "local"
	SourceUpstream Source = "upstream"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceLocal, SourceUpstream:
		return nil
	default:
		return fmt.Errorf("mcpcalllog: invalid enum value for source field: %q", s)
	}
}

// Transport defines the type for the "transport" enum field.
type Transport string

// TransportStreamableHTTP is the default value of the Transport enum.
const DefaultTransport = TransportStreamableHTTP

// Transport values.
const (
	TransportStreamableHTTP Transport = "streamable_http"
	TransportSse            Transport = "sse"
	TransportHTTP           Transport = "http"
)

func (t Transport) String() string {
	return string(t)
}

// TransportValidator is a validator for the "transport" field enum values. It is called by the builders before save.
func TransportValidator(t Transport) error {
	switch t {
	case TransportStreamableHTTP, TransportSse, TransportHTTP:
		return nil
	default:
		return fmt.Errorf("mcpcalllog: invalid enum value for transport field: %q", t)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusSuccess is the default value of the Status enum.
const DefaultStatus = StatusSuccess

// Status values.
const (
	StatusSuccess Status = "success"
	StatusError   Status = "error"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSuccess, StatusError:
		return nil
	default:
		return fmt.Errorf("mcpcalllog: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MCPCallLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByTransport orders the results by the transport field.
func ByTransport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransport, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByProviderSlug orders the results by the provider_slug field.
func ByProviderSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSlug, opts...).ToFunc()
}

// ByTokenPrefix orders the results by the token_prefix field.
func ByTokenPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenPrefix, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
