// Code generated by ent, DO NOT EDIT.

package mcpcalllog

import (
	"lazycat-mcp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldID, id))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldMethod, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldTarget, v))
}

// ProviderSlug applies equality check predicate on the "provider_slug" field. It's identical to ProviderSlugEQ.
func ProviderSlug(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldProviderSlug, v))
}

// TokenPrefix applies equality check predicate on the "token_prefix" field. It's identical to TokenPrefixEQ.
func TokenPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldTokenPrefix, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldSessionID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldRequestID, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldDurationMs, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldCreatedAt, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldSource, vs...))
}

// TransportEQ applies the EQ predicate on the "transport" field.
func TransportEQ(v Transport) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldTransport, v))
}

// TransportNEQ applies the NEQ predicate on the "transport" field.
func TransportNEQ(v Transport) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldTransport, v))
}

// TransportIn applies the In predicate on the "transport" field.
func TransportIn(vs ...Transport) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldTransport, vs...))
}

// TransportNotIn applies the NotIn predicate on the "transport" field.
func TransportNotIn(vs ...Transport) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldTransport, vs...))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldMethod, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldTarget, v))
}

// ProviderSlugEQ applies the EQ predicate on the "provider_slug" field.
func ProviderSlugEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldProviderSlug, v))
}

// ProviderSlugNEQ applies the NEQ predicate on the "provider_slug" field.
func ProviderSlugNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldProviderSlug, v))
}

// ProviderSlugIn applies the In predicate on the "provider_slug" field.
func ProviderSlugIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldProviderSlug, vs...))
}

// ProviderSlugNotIn applies the NotIn predicate on the "provider_slug" field.
func ProviderSlugNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldProviderSlug, vs...))
}

// ProviderSlugGT applies the GT predicate on the "provider_slug" field.
func ProviderSlugGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldProviderSlug, v))
}

// ProviderSlugGTE applies the GTE predicate on the "provider_slug" field.
func ProviderSlugGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldProviderSlug, v))
}

// ProviderSlugLT applies the LT predicate on the "provider_slug" field.
func ProviderSlugLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldProviderSlug, v))
}

// ProviderSlugLTE applies the LTE predicate on the "provider_slug" field.
func ProviderSlugLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldProviderSlug, v))
}

// ProviderSlugContains applies the Contains predicate on the "provider_slug" field.
func ProviderSlugContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldProviderSlug, v))
}

// ProviderSlugHasPrefix applies the HasPrefix predicate on the "provider_slug" field.
func ProviderSlugHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldProviderSlug, v))
}

// ProviderSlugHasSuffix applies the HasSuffix predicate on the "provider_slug" field.
func ProviderSlugHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldProviderSlug, v))
}

// ProviderSlugIsNil applies the IsNil predicate on the "provider_slug" field.
func ProviderSlugIsNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIsNull(FieldProviderSlug))
}

// ProviderSlugNotNil applies the NotNil predicate on the "provider_slug" field.
func ProviderSlugNotNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotNull(FieldProviderSlug))
}

// ProviderSlugEqualFold applies the EqualFold predicate on the "provider_slug" field.
func ProviderSlugEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldProviderSlug, v))
}

// ProviderSlugContainsFold applies the ContainsFold predicate on the "provider_slug" field.
func ProviderSlugContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldProviderSlug, v))
}

// TokenPrefixEQ applies the EQ predicate on the "token_prefix" field.
func TokenPrefixEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenPrefixNEQ applies the NEQ predicate on the "token_prefix" field.
func TokenPrefixNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldTokenPrefix, v))
}

// TokenPrefixIn applies the In predicate on the "token_prefix" field.
func TokenPrefixIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldTokenPrefix, vs...))
}

// TokenPrefixNotIn applies the NotIn predicate on the "token_prefix" field.
func TokenPrefixNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldTokenPrefix, vs...))
}

// TokenPrefixGT applies the GT predicate on the "token_prefix" field.
func TokenPrefixGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldTokenPrefix, v))
}

// TokenPrefixGTE applies the GTE predicate on the "token_prefix" field.
func TokenPrefixGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldTokenPrefix, v))
}

// TokenPrefixLT applies the LT predicate on the "token_prefix" field.
func TokenPrefixLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldTokenPrefix, v))
}

// TokenPrefixLTE applies the LTE predicate on the "token_prefix" field.
func TokenPrefixLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldTokenPrefix, v))
}

// TokenPrefixContains applies the Contains predicate on the "token_prefix" field.
func TokenPrefixContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldTokenPrefix, v))
}

// TokenPrefixHasPrefix applies the HasPrefix predicate on the "token_prefix" field.
func TokenPrefixHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldTokenPrefix, v))
}

// TokenPrefixHasSuffix applies the HasSuffix predicate on the "token_prefix" field.
func TokenPrefixHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldTokenPrefix, v))
}

// TokenPrefixIsNil applies the IsNil predicate on the "token_prefix" field.
func TokenPrefixIsNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIsNull(FieldTokenPrefix))
}

// TokenPrefixNotNil applies the NotNil predicate on the "token_prefix" field.
func TokenPrefixNotNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotNull(FieldTokenPrefix))
}

// TokenPrefixEqualFold applies the EqualFold predicate on the "token_prefix" field.
func TokenPrefixEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldTokenPrefix, v))
}

// TokenPrefixContainsFold applies the ContainsFold predicate on the "token_prefix" field.
func TokenPrefixContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldTokenPrefix, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDIsNil applies the IsNil predicate on the "session_id" field.
func SessionIDIsNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIsNull(FieldSessionID))
}

// SessionIDNotNil applies the NotNil predicate on the "session_id" field.
func SessionIDNotNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotNull(FieldSessionID))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldSessionID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldRequestID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldStatusCode, v))
}

// StatusCodeIsNil applies the IsNil predicate on the "status_code" field.
func StatusCodeIsNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIsNull(FieldStatusCode))
}

// StatusCodeNotNil applies the NotNil predicate on the "status_code" field.
func StatusCodeNotNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotNull(FieldStatusCode))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldDurationMs, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MCPCallLog) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MCPCallLog) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MCPCallLog) predicate.MCPCallLog {
	return predicate.MCPCallLog(sql.NotPredicates(p))
}
