// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MCPToken is the predicate function for mcptoken builders.
type MCPToken func(*sql.Selector)

// UpstreamProvider is the predicate function for upstreamprovider builders.
type UpstreamProvider func(*sql.Selector)
